from django.urls import path
from . import views, supervised_views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('setup/', views.clinic_setup_view, name='clinic_setup'),
    path('plan/', views.plan_view, name='plan'),
    path('staff/', views.staff_list_view, name='staff_list'),
    path('staff/add/', views.add_staff_view, name='add_staff'),
    path('staff/<int:pk>/edit/', views.edit_staff_view, name='edit_staff'),
    path('staff/<int:pk>/delete/', views.delete_staff_view, name='delete_staff'),
    path('register/', views.register_view, name='register'),
    path('register/success/', views.register_success_view, name='register_success'),
    path('admin-panel/', views.admin_panel_view, name='admin_panel'),
    path('admin-panel/approve/<int:pk>/', views.approve_registration_view, name='approve_registration'),
    path('admin-panel/reject/<int:pk>/', views.reject_registration_view, name='reject_registration'),
    path('admin-panel/message/<int:pk>/read/', views.mark_contact_read_view, name='mark_contact_read'),
    path('contact/', views.contact_view, name='contact'),
    path('contact/success/', views.contact_success_view, name='contact_success'),
    path('api/preference/', views.update_preference_api, name='update_preference'),
    path('letterhead/', views.letterhead_view, name='letterhead'),
    path('admin-panel/check-user/<str:phone>/', views.check_user_view, name='check_user'),
    path('admin-panel/reset-password/<int:pk>/', views.reset_clinic_password_view, name='reset_clinic_password'),
    path('admin-panel/pw-reset/<int:pk>/', views.superuser_reset_password_view, name='superuser_reset_password'),
    path('switch-clinic/', views.switch_clinic_view, name='switch_clinic'),
    path('add-clinic/', views.add_clinic_view, name='add_clinic'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('staff/<int:pk>/reset-password/', views.staff_reset_password_view, name='staff_reset_password'),
    path('update-email/', views.update_email_view, name='update_email'),
    path('change-password/', views.change_password_view, name='change_password'),
    path('clinic/edit/', views.clinic_edit_view, name='clinic_edit'),
    path('clinic/<int:pk>/delete/', views.clinic_delete_view, name='clinic_delete'),
    path('clinic/request-deletion/', views.request_clinic_deletion_view, name='request_clinic_deletion'),
    path('admin-panel/clinic-deletion/<int:pk>/approve/', views.approve_clinic_deletion_view, name='approve_clinic_deletion'),
    path('admin-panel/clinic-deletion/<int:pk>/reject/', views.reject_clinic_deletion_view, name='reject_clinic_deletion'),
    path('executives/', views.executive_list_view, name='executive_list'),
    path('executives/register/', views.executive_register_view, name='executive_register'),
    path('executives/register/success/', views.executive_register_success_view, name='executive_register_success'),
    path('executives/<int:pk>/mobile/', views.executive_mobile_view, name='executive_mobile'),

    # Supervised actions
    path('supervised/', supervised_views.supervised_pending_view, name='supervised_pending'),
    path('supervised/api/request/', supervised_views.request_action_api, name='supervised_request'),
    path('supervised/api/poll/<uuid:request_id>/', supervised_views.poll_action_api, name='supervised_poll'),
    path('supervised/api/cancel/<uuid:request_id>/', supervised_views.cancel_action_api, name='supervised_cancel'),
    path('supervised/api/count/', supervised_views.pending_count_api, name='supervised_count'),
    path('supervised/api/pending/', supervised_views.pending_actions_api, name='supervised_pending_api'),
    path('supervised/api/resolve/<uuid:request_id>/', supervised_views.resolve_action_api, name='supervised_resolve'),
    path('supervised/api/bulk-resolve/', supervised_views.bulk_resolve_api, name='supervised_bulk_resolve'),
    path('supervised/log/', supervised_views.supervised_log_view, name='supervised_log'),
]
