# Generated by Django 5.2.10 on 2026-03-10 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_replace_with_catalog_and_favorites'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('generic_name', models.CharField(db_index=True, max_length=250)),
                ('form', models.CharField(blank=True, max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['generic_name'], name='pharmacy_me_generic_d175e8_idx'), models.Index(fields=['name'], name='pharmacy_me_name_6a5b09_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=250)),
                ('default_form', models.CharField(blank=True, max_length=30)),
                ('default_dosage', models.CharField(blank=True, max_length=50)),
                ('default_frequency', models.CharField(blank=True, max_length=100)),
                ('default_duration', models.CharField(blank=True, max_length=50)),
                ('default_notes', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_medicines', to='accounts.staffmember')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicinecatalog')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=250)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('reorder_flagged', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_items', to='accounts.clinic')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicinecatalog')),
            ],
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.AddIndex(
            model_name='pharmacyitem',
            index=models.Index(fields=['clinic', 'medicine'], name='pharmacy_ph_clinic__ad32f8_idx'),
        ),
    ]
