# Generated by Django 5.2.10 on 2026-03-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_pharmacybatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyitem',
            name='custom_generic_name',
            field=models.CharField(blank=True, help_text='Generic/active ingredient for custom medicines (e.g. Clindamycin 1% w/w)', max_length=250),
        ),
    ]
