# Generated by Django 5.2.10 on 2026-03-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffmember_user_fk'),
        ('pharmacy', '0004_pharmacyitem_custom_generic_name'),
        ('prescription', '0006_add_drug_interactions'),
        ('reception', '0002_visit_cancellation_reason_alter_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_substitute', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.pharmacybatch')),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffmember')),
                ('pharmacy_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.pharmacyitem')),
                ('prescription_med', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription.prescriptionmedicine')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_items', to='reception.visit')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=30, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], default='cash', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffmember')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_bill', to='reception.visit')),
            ],
        ),
    ]
