# Generated by Django 5.2.10 on 2026-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=200)),
                ('clinic_type', models.CharField(choices=[('general', 'General Practice / GP'), ('specialist', 'Specialist Clinic'), ('multispecialty', 'Multi-specialty'), ('dental', 'Dental'), ('pediatric', 'Pediatric'), ('other', 'Other')], default='general', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('clinic_phone', models.CharField(max_length=15)),
                ('doctor_name', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password_hash', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
