# Generated by Django 5.2.10 on 2026-03-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinicregistrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('inquiry_type', models.CharField(choices=[('new_clinic', 'Interested in joining ClinicAI'), ('existing', 'I am an existing clinic'), ('pricing', 'Pricing question'), ('support', 'Technical support'), ('other', 'Other')], default='new_clinic', max_length=20)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
