# Generated by Django 5.2.10 on 2026-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='show_rx_remarks',
            field=models.BooleanField(default=True),
        ),
    ]
