# Generated by Django 5.2.10 on 2026-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_replace_with_catalog_and_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='letterhead_height_mm',
            field=models.PositiveSmallIntegerField(default=0, help_text='Height of the printed letterhead area in mm. Prescription content starts below this.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='letterhead_image',
            field=models.ImageField(blank=True, null=True, upload_to='letterheads/'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='use_letterhead',
            field=models.BooleanField(default=False, help_text='If True, hide digital header and start content below letterhead_height_mm.'),
        ),
    ]
