# Generated by Django 5.2.10 on 2026-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_clinicaiexecutive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaiexecutive',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clinicregistrationrequest',
            name='referred_by_mobile',
            field=models.CharField(blank=True, help_text='Mobile number of the ClinicAI Executive who referred this clinic.', max_length=10),
        ),
    ]
