# Generated by Django 5.2.10 on 2026-04-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_supervised_action_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisedactionrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
