# Generated by Django 5.2.10 on 2026-03-07 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_number', models.PositiveIntegerField()),
                ('chief_complaint', models.CharField(blank=True, max_length=300)),
                ('vitals_bp', models.CharField(blank=True, max_length=20)),
                ('vitals_temp', models.CharField(blank=True, max_length=10)),
                ('vitals_weight', models.CharField(blank=True, max_length=10)),
                ('vitals_spo2', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('done', 'Done'), ('no_show', 'No Show')], default='waiting', max_length=20)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='reception.patient')),
            ],
            options={
                'ordering': ['token_number'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'phone'], name='reception_p_clinic__ab5dc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('clinic', 'phone')},
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['clinic', 'visit_date', 'status'], name='reception_v_clinic__38de75_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-visit_date'], name='reception_v_patient_2cf03e_idx'),
        ),
    ]
