# Generated by Django 5.2.10 on 2026-03-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('patient_called', 'Patient called to cancel'), ('rescheduled', 'Rescheduled'), ('doctor_unavailable', 'Doctor unavailable'), ('patient_unwell', 'Patient unwell / hospitalised'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('done', 'Done'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
