# Generated by Django 5.2.10 on 2026-03-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='differential_diagnoses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='investigations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='selected_diagnosis',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
