# Generated by Django 5.2.10 on 2026-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_add_differential_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=300)),
                ('category', models.CharField(choices=[('symptom', 'Symptom'), ('diagnosis', 'Diagnosis'), ('investigation', 'Investigation'), ('procedure', 'Procedure'), ('medicine', 'Medicine'), ('advice', 'Advice')], max_length=20)),
                ('aliases', models.TextField(blank=True)),
                ('specialty', models.CharField(blank=True, max_length=50)),
                ('icd_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'term'], name='prescriptio_categor_108d75_idx'), models.Index(fields=['specialty', 'term'], name='prescriptio_special_523ba5_idx')],
            },
        ),
    ]
