# Generated by Django 5.2.10 on 2026-03-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_medicalterm_weight_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='clinical_evaluation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='investigations_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='validity_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
