# Generated by Django 5.2.10 on 2026-03-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_prescription_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug1_keyword', models.CharField(db_index=True, max_length=100)),
                ('drug2_keyword', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('major', 'Major — avoid combination'), ('moderate', 'Moderate — monitor closely'), ('minor', 'Minor — use with caution')], default='moderate', max_length=10)),
                ('effect', models.CharField(help_text="What happens (e.g. 'Increased bleeding risk')", max_length=300)),
                ('mechanism', models.CharField(blank=True, help_text='Brief mechanism', max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['drug1_keyword'], name='prescriptio_drug1_k_d98234_idx'), models.Index(fields=['drug2_keyword'], name='prescriptio_drug2_k_2cc63e_idx')],
                'unique_together': {('drug1_keyword', 'drug2_keyword')},
            },
        ),
    ]
