# Generated by Django 5.2.10 on 2026-03-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_prescription_comorbidities_history_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='route',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
