"""Seed MedicalTerm with symptoms, diagnoses, investigations, and advice."""
from django.core.management.base import BaseCommand
from prescription.models import MedicalTerm


class Command(BaseCommand):
    help = 'Seed medical terms (symptoms, diagnoses, investigations, advice)'

    def handle(self, *args, **options):
        if MedicalTerm.objects.exists():
            self.stdout.write('MedicalTerm already seeded — skipping. Use shell to reseed.')
            return
        items = []

        def t(term, category, aliases='', specialty='', icd_code=''):
            return MedicalTerm(term=term, category=category, aliases=aliases,
                               specialty=specialty, icd_code=icd_code)

        # ── Symptoms ───────────────────────────────────────────────────
        items += [
            t('Fever', 'symptom', 'bukhar, bukhaar, jwar, pyrexia', '', 'R50'),
            t('Cough', 'symptom', 'khansi, khaansi, khasi', '', 'R05'),
            t('Sore throat', 'symptom', 'gala dard, gale mein dard, gale mein kharash', '', 'J02'),
            t('Headache', 'symptom', 'sir dard, sar dard, sardard, cephalalgia', '', 'R51'),
            t('Dizziness', 'symptom', 'chakkar, chakkar aana, vertigo', '', 'R42'),
            t('Chest pain', 'symptom', 'seene mein dard, seene ka dard, chest mein dard', '', 'R07'),
            t('Palpitations', 'symptom', 'dil ki dhadkan, dhadkan tez hona', '', 'R00'),
            t('Shortness of breath', 'symptom', 'sans lene mein takleef, dam phoolna, dyspnoea, breathlessness', '', 'R06'),
            t('Fatigue', 'symptom', 'thakaan, kamzori, tiredness, lethargy', '', 'R53'),
            t('Weakness', 'symptom', 'kamzori, taakat na hona, asthenia', '', 'R53'),
            t('Weight loss', 'symptom', 'wajan ghatna, vajan kam hona', '', 'R63.4'),
            t('Weight gain', 'symptom', 'wajan badhna, motapa', '', 'R63.5'),
            t('Abdominal pain', 'symptom', 'pet dard, pet mein dard, pait mein dard, stomach pain', '', 'R10'),
            t('Nausea', 'symptom', 'ji matlana, jee machlana, ulti jaisi feeling', '', 'R11'),
            t('Vomiting', 'symptom', 'ulti, vomit karna, vomiting', '', 'R11'),
            t('Diarrhea', 'symptom', 'dast, loose motions, loose stool, latrine banana', '', 'R19.7'),
            t('Constipation', 'symptom', 'kabz, qabz, kabziyat, qabziyat', '', 'K59.0'),
            t('Bloating', 'symptom', 'pet phoolna, gas hona, afara', '', 'R14'),
            t('Heartburn', 'symptom', 'seene mein jalan, acidity, acid reflux, jalan', '', 'R12'),
            t('Jaundice', 'symptom', 'piliya, jaundice', '', 'R17'),
            t('Back pain', 'symptom', 'kamar dard, kamar mein dard, peeth mein dard', '', 'M54'),
            t('Neck pain', 'symptom', 'gardan dard, gardan mein dard, cervicalgia', '', 'M54.2'),
            t('Joint pain', 'symptom', 'jodo ka dard, jodo mein dard, arthralgia', '', 'M25.5'),
            t('Muscle pain', 'symptom', 'maansapeshiyo mein dard, myalgia, body ache', '', 'M79.1'),
            t('Swelling of feet', 'symptom', 'paon sujan, pair mein sujan, pedal oedema', '', 'R60'),
            t('Leg cramps', 'symptom', 'pair mein khichaav, tang mein dard', '', 'R25.2'),
            t('Burning urination', 'symptom', 'peshab mein jalan, dysuria', '', 'R30.0'),
            t('Frequent urination', 'symptom', 'baar baar peshab, frequent urination, pollakiuria', '', 'R35'),
            t('Blood in urine', 'symptom', 'peshab mein khoon, haematuria', '', 'R31'),
            t('Difficulty urinating', 'symptom', 'peshab rokna, peshab mein takleef', '', 'R33'),
            t('Rash', 'symptom', 'daane, chhale, skin rash, chehre par daane', '', 'R21'),
            t('Itching', 'symptom', 'khujli, khaarish, pruritus', '', 'L29'),
            t('Hair loss', 'symptom', 'baal jhadna, baal girna, alopecia', '', 'L65'),
            t('Dry skin', 'symptom', 'ruki hui twacha, khushk twacha, xerosis', '', 'L85.3'),
            t('Blurred vision', 'symptom', 'dhundhla dikhna, aankhon se dhundha, visual blurring', '', 'H53.8'),
            t('Eye redness', 'symptom', 'aankhein laal hona, conjunctival redness', '', 'H57.8'),
            t('Ear pain', 'symptom', 'kaan mein dard, otalgia', '', 'H92.0'),
            t('Nasal congestion', 'symptom', 'naak band hona, band naak, nasal block', '', 'R09.8'),
            t('Runny nose', 'symptom', 'naak behna, rhinorrhoea', '', 'J00'),
            t('Sneezing', 'symptom', 'chhink aana, sneeze', '', 'R06.7'),
            t('Insomnia', 'symptom', 'neend na aana, neend ki kami, sleep disturbance', '', 'G47.0'),
            t('Anxiety', 'symptom', 'chinta, ghabrahat, anxious', '', 'F41.1'),
            t('Tremors', 'symptom', 'haath kaampna, kaampna, shaking', '', 'R25.1'),
            t('Seizures', 'symptom', 'mirchhiyan, fits, convulsions', '', 'R56.8'),
            t('Numbness', 'symptom', 'sunn hona, sansanahat, hypoaesthesia', '', 'R20.0'),
            t('Tingling', 'symptom', 'jhanjhanahat, pins and needles, paraesthesia', '', 'R20.2'),
            t('Memory loss', 'symptom', 'yaad na rehna, bhoolna, amnesia', '', 'R41.3'),
            t('Confusion', 'symptom', 'ulajhan, ghbrahat, disorientation', '', 'R41.0'),
            t('Excessive thirst', 'symptom', 'bahut pyaas lagni, polydipsia', '', 'R63.1'),
            t('Excessive hunger', 'symptom', 'bahut bhook lagni, polyphagia', '', 'R63.2'),
            t('Sweating', 'symptom', 'paseena aana, diaphoresis, hyperhidrosis', '', 'R61'),
            t('Cold intolerance', 'symptom', 'thand se takleef hona', '', ''),
            t('Heat intolerance', 'symptom', 'garmi se takleef hona', '', ''),
            t('Irregular periods', 'symptom', 'machlik cycles, irregular menstruation, dysmenorrhoea', '', 'N92'),
            t('Painful periods', 'symptom', 'masik mein dard, period mein dard, dysmenorrhoea', '', 'N94.4'),
            t('Vaginal discharge', 'symptom', 'safed pani, leucorrhoea, vaginal discharge', '', 'N89.8'),
        ]

        # ── Diagnoses ──────────────────────────────────────────────────
        items += [
            t('Type 2 Diabetes Mellitus', 'diagnosis', 'T2DM, sugar, madhumeh, diabetes', '', 'E11'),
            t('Type 1 Diabetes Mellitus', 'diagnosis', 'T1DM, juvenile diabetes', '', 'E10'),
            t('Essential Hypertension', 'diagnosis', 'BP high, high BP, blood pressure, hypertension', '', 'I10'),
            t('Acute Pharyngitis', 'diagnosis', 'sore throat, gala kharab, throat infection', '', 'J02'),
            t('Acute Tonsillitis', 'diagnosis', 'tonsil, tonsils, tonsil infection', '', 'J03'),
            t('Upper Respiratory Tract Infection', 'diagnosis', 'URTI, common cold, nazla, zukam', '', 'J06'),
            t('Pneumonia', 'diagnosis', 'niwmonia, lung infection, pneumonitis', '', 'J18'),
            t('Bronchial Asthma', 'diagnosis', 'asthma, daama, daama ki bimari, wheezing', '', 'J45'),
            t('COPD', 'diagnosis', 'chronic obstructive pulmonary disease, chronic bronchitis', '', 'J44'),
            t('Coronary Artery Disease', 'diagnosis', 'CAD, heart disease, ischemic heart disease', '', 'I25'),
            t('Acute MI', 'diagnosis', 'heart attack, myocardial infarction, AMI', '', 'I21'),
            t('Heart Failure', 'diagnosis', 'cardiac failure, heart failure, congestive heart failure', '', 'I50'),
            t('Atrial Fibrillation', 'diagnosis', 'AF, AFib, irregular heartbeat', '', 'I48'),
            t('Hypothyroidism', 'diagnosis', 'thyroid kam hona, low thyroid, thyroid deficiency', '', 'E03'),
            t('Hyperthyroidism', 'diagnosis', 'thyroid zyada hona, overactive thyroid, thyrotoxicosis', '', 'E05'),
            t('GERD', 'diagnosis', 'acid reflux, gastroesophageal reflux, heartburn disease', '', 'K21'),
            t('Peptic Ulcer', 'diagnosis', 'stomach ulcer, gastric ulcer, duodenal ulcer', '', 'K27'),
            t('Irritable Bowel Syndrome', 'diagnosis', 'IBS, stomach problem, bowel disease', '', 'K58'),
            t('Appendicitis', 'diagnosis', 'appendix, appendix mein dard', '', 'K37'),
            t('Cholecystitis', 'diagnosis', 'gallbladder inflammation, gallbladder problem', '', 'K81'),
            t('Acute Gastroenteritis', 'diagnosis', 'stomach bug, food poisoning, AGE, gastro', '', 'A09'),
            t('Typhoid Fever', 'diagnosis', 'typhoid, enteric fever, typhoid bukhar', '', 'A01'),
            t('Malaria', 'diagnosis', 'maleria, malarial fever', '', 'B54'),
            t('Dengue Fever', 'diagnosis', 'dengue, dengue bukhar, dengue fever', '', 'A97'),
            t('Chikungunya', 'diagnosis', 'chikungunya fever, chiku fever', '', 'A92'),
            t('COVID-19', 'diagnosis', 'covid, corona, coronavirus', '', 'U07'),
            t('Urinary Tract Infection', 'diagnosis', 'UTI, peshab ki infection, urine infection', '', 'N39'),
            t('Pyelonephritis', 'diagnosis', 'kidney infection, gurdey ki infection', '', 'N12'),
            t('Acute Kidney Injury', 'diagnosis', 'AKI, acute renal failure', '', 'N17'),
            t('Chronic Kidney Disease', 'diagnosis', 'CKD, chronic renal failure, kidney failure', '', 'N18'),
            t('Iron Deficiency Anaemia', 'diagnosis', 'anaemia, anemia, khoon ki kami, iron deficiency', '', 'D50'),
            t('Vitamin B12 Deficiency', 'diagnosis', 'B12 deficiency, cobalamin deficiency', '', 'E53'),
            t('Migraine', 'diagnosis', 'migraine, migrain, vascular headache', '', 'G43'),
            t('Tension Headache', 'diagnosis', 'tension headache, stress headache', '', 'G44'),
            t('Epilepsy', 'diagnosis', 'epilepsy, fits, seizure disorder, mirchhiyan', '', 'G40'),
            t('Depression', 'diagnosis', 'depresion, sadness, mood disorder', '', 'F32'),
            t('Anxiety Disorder', 'diagnosis', 'anxiety, ghabrahat, worry disorder', '', 'F41'),
            t('Schizophrenia', 'diagnosis', 'psychosis, schizophrenia', '', 'F20'),
            t('Osteoarthritis', 'diagnosis', 'OA, joint degeneration, ghutne mein dard', '', 'M19'),
            t('Rheumatoid Arthritis', 'diagnosis', 'RA, inflammatory arthritis', '', 'M05'),
            t('Gout', 'diagnosis', 'uric acid, gouty arthritis', '', 'M10'),
            t('Osteoporosis', 'diagnosis', 'bone density loss, haddi kamzor hona', '', 'M81'),
            t('Lumbar Spondylosis', 'diagnosis', 'lumber spondylosis, kamar ki haddi, degenerative spine', '', 'M47'),
            t('Cervical Spondylosis', 'diagnosis', 'cervical, gardan ki haddi, neck spondylosis', '', 'M47'),
            t('Sciatica', 'diagnosis', 'scitica, sciatic nerve pain, leg pain from spine', '', 'M54.4'),
            t('Carpal Tunnel Syndrome', 'diagnosis', 'CTS, wrist nerve compression, hand numbness', '', 'G56'),
            t('Contact Dermatitis', 'diagnosis', 'skin allergy, contact rash', '', 'L25'),
            t('Psoriasis', 'diagnosis', 'psoriasis, skin plaques, scaly skin', '', 'L40'),
            t('Acne Vulgaris', 'diagnosis', 'acne, pimples, muhaase', '', 'L70'),
            t('Fungal Skin Infection', 'diagnosis', 'ringworm, tinea, daad, fungal rash', '', 'B35'),
            t('Eczema', 'diagnosis', 'atopic dermatitis, skin inflammation, kharish', '', 'L20'),
            t('Urticaria', 'diagnosis', 'hives, allergic rash, pitti, urticaria', '', 'L50'),
            t('Type 2 Diabetes with Nephropathy', 'diagnosis', 'diabetic kidney disease, diabetic nephropathy', '', 'E11.2'),
            t('Diabetic Neuropathy', 'diagnosis', 'diabetes nerve damage, neuropathy', '', 'E11.4'),
            t('Diabetic Retinopathy', 'diagnosis', 'diabetes eye complication, retinopathy', '', 'E11.3'),
            t('Hypertensive Heart Disease', 'diagnosis', 'hypertensive cardiomyopathy', '', 'I11'),
            t('Metabolic Syndrome', 'diagnosis', 'metabolic syndrome, insulin resistance', '', 'E88.81'),
            t('PCOS/PCOD', 'diagnosis', 'polycystic ovary, PCOD, PCOS, cysts in ovary', '', 'E28.2'),
            t('Hyperlipidaemia', 'diagnosis', 'high cholesterol, dyslipidaemia, lipid problem', '', 'E78'),
            t('Non-alcoholic Fatty Liver Disease', 'diagnosis', 'NAFLD, fatty liver, liver mein fat', '', 'K76.0'),
            t('Viral Fever', 'diagnosis', 'viral bukhar, dengue like fever, viral infection', '', 'A99'),
            t('Dengue with Thrombocytopenia', 'diagnosis', 'dengue with low platelets', '', 'A97'),
            t('Benign Prostatic Hyperplasia', 'diagnosis', 'BPH, prostate enlargement, enlarged prostate', '', 'N40'),
            t('Erectile Dysfunction', 'diagnosis', 'ED, sexual dysfunction, mardaana kamzori', '', 'N52'),
            t('Hashimoto Thyroiditis', 'diagnosis', "hashimoto's thyroiditis, autoimmune thyroid", '', 'E06.3'),
            t('Graves Disease', 'diagnosis', "grave's disease, toxic goitre", '', 'E05.0'),
            t('Hypothyroidism on Thyroxine Replacement', 'diagnosis', 'hypothyroid on treatment, thyroxine replacement', '', 'E03'),
        ]

        # ── Investigations ─────────────────────────────────────────────
        items += [
            t('CBC (Complete Blood Count)', 'investigation', 'complete blood count, blood test, CBC', '', ''),
            t('Haemoglobin', 'investigation', 'Hb, hemoglobin, blood count', '', ''),
            t('WBC Count', 'investigation', 'white blood cell, leucocyte count, total count', '', ''),
            t('Platelet Count', 'investigation', 'platelets, thrombocyte count', '', ''),
            t('PCV (Packed Cell Volume)', 'investigation', 'haematocrit, hematocrit', '', ''),
            t('ESR', 'investigation', 'erythrocyte sedimentation rate, ESR test', '', ''),
            t('CRP (C-Reactive Protein)', 'investigation', 'C reactive protein, inflammatory marker', '', ''),
            t('Blood Glucose Fasting (FBS)', 'investigation', 'fasting blood sugar, FBS, fasting glucose', '', ''),
            t('Blood Glucose Post Prandial (PPBS)', 'investigation', 'PPBS, post meal sugar, 2 hour glucose', '', ''),
            t('HbA1c', 'investigation', 'glycosylated haemoglobin, A1c, long term sugar', '', ''),
            t('Lipid Profile', 'investigation', 'cholesterol test, lipid panel, lipids', '', ''),
            t('Total Cholesterol', 'investigation', 'cholesterol, total cholesterol', '', ''),
            t('LDL Cholesterol', 'investigation', 'bad cholesterol, LDL', '', ''),
            t('HDL Cholesterol', 'investigation', 'good cholesterol, HDL', '', ''),
            t('Triglycerides', 'investigation', 'triglyceride, TG level', '', ''),
            t('Liver Function Test (LFT)', 'investigation', 'liver test, LFT, liver profile', '', ''),
            t('SGOT (AST)', 'investigation', 'AST, SGOT, aspartate aminotransferase', '', ''),
            t('SGPT (ALT)', 'investigation', 'ALT, SGPT, alanine aminotransferase', '', ''),
            t('Serum Bilirubin', 'investigation', 'bilirubin, jaundice test', '', ''),
            t('Alkaline Phosphatase', 'investigation', 'ALP, bone/liver enzyme', '', ''),
            t('Serum Albumin', 'investigation', 'albumin, protein level', '', ''),
            t('Kidney Function Test (KFT)', 'investigation', 'kidney test, renal function test, KFT, RFT', '', ''),
            t('Serum Creatinine', 'investigation', 'creatinine, kidney creatinine', '', ''),
            t('Blood Urea', 'investigation', 'urea, BUN, blood urea nitrogen', '', ''),
            t('Serum Uric Acid', 'investigation', 'uric acid test', '', ''),
            t('eGFR', 'investigation', 'estimated glomerular filtration rate, kidney function', '', ''),
            t('Serum Electrolytes', 'investigation', 'electrolytes, sodium potassium', '', ''),
            t('Sodium', 'investigation', 'Na, serum sodium', '', ''),
            t('Potassium', 'investigation', 'K, serum potassium', '', ''),
            t('Thyroid Profile', 'investigation', 'thyroid test, T3 T4 TSH, thyroid function test', '', ''),
            t('TSH', 'investigation', 'thyroid stimulating hormone, TSH level', '', ''),
            t('T3', 'investigation', 'triiodothyronine, T3 level', '', ''),
            t('T4', 'investigation', 'thyroxine, T4 level', '', ''),
            t('Free T4', 'investigation', 'free thyroxine, FT4', '', ''),
            t('Iron Studies', 'investigation', 'iron, serum iron, iron profile', '', ''),
            t('Serum Ferritin', 'investigation', 'ferritin, iron stores', '', ''),
            t('Serum B12', 'investigation', 'vitamin B12 level, cobalamin', '', ''),
            t('Serum Folate', 'investigation', 'folic acid level, folate', '', ''),
            t('Serum Calcium', 'investigation', 'calcium level, serum calcium', '', ''),
            t('Serum Phosphorus', 'investigation', 'phosphorus, phosphate', '', ''),
            t('Vitamin D (25-OH)', 'investigation', 'vitamin D level, 25 hydroxy vitamin D', '', ''),
            t('Urine Routine (R/M)', 'investigation', 'urine routine examination, urine RE/ME, urine test', '', ''),
            t('Urine Culture and Sensitivity', 'investigation', 'urine culture, C&S, urine sensitivity test', '', ''),
            t('24-hour Urine Protein', 'investigation', '24 hour urine protein, proteinuria test', '', ''),
            t('Stool Routine', 'investigation', 'stool examination, stool test', '', ''),
            t('Stool Culture', 'investigation', 'stool culture, stool sensitivity', '', ''),
            t('Blood Culture', 'investigation', 'blood culture, bacteremia test', '', ''),
            t('Dengue NS1 Antigen', 'investigation', 'dengue NS1, dengue antigen', '', ''),
            t('Dengue IgM/IgG', 'investigation', 'dengue antibody, dengue serology', '', ''),
            t('Malaria Antigen Test', 'investigation', 'malaria test, RDT malaria', '', ''),
            t('Widal Test', 'investigation', 'typhoid test, widal', '', ''),
            t('HBsAg', 'investigation', 'hepatitis B, HBsAg, hepatitis surface antigen', '', ''),
            t('Anti-HCV', 'investigation', 'hepatitis C, HCV antibody', '', ''),
            t('HIV ELISA', 'investigation', 'HIV test, AIDS test, HIV antibody', '', ''),
            t('VDRL', 'investigation', 'syphilis test, VDRL, RPR', '', ''),
            t('ANA (Antinuclear Antibody)', 'investigation', 'ANA test, antinuclear, autoimmune', '', ''),
            t('RF (Rheumatoid Factor)', 'investigation', 'rheumatoid factor, RA factor', '', ''),
            t('Anti-CCP', 'investigation', 'anti cyclic citrullinated peptide, RA antibody', '', ''),
            t('ANCA', 'investigation', 'antineutrophil cytoplasmic, vasculitis test', '', ''),
            t('PSA (Prostate Specific Antigen)', 'investigation', 'PSA, prostate test', '', ''),
            t('CA-125', 'investigation', 'ovarian cancer marker, CA125', '', ''),
            t('AFP', 'investigation', 'alpha fetoprotein, liver cancer marker', '', ''),
            t('CEA', 'investigation', 'carcinoembryonic antigen, cancer marker', '', ''),
            t('X-Ray Chest PA', 'investigation', 'chest X-ray, CXR, PA view chest', '', ''),
            t('X-Ray Lumbar Spine', 'investigation', 'lumbar X-ray, spine X-ray', '', ''),
            t('X-Ray Knee', 'investigation', 'knee X-ray, knee radiograph', '', ''),
            t('ECG (12-lead)', 'investigation', 'ECG, electrocardiogram, heart tracing', '', ''),
            t('2D Echocardiography', 'investigation', '2D echo, echo, cardiac echo', '', ''),
            t('TMT (Treadmill Test)', 'investigation', 'treadmill test, stress test, exercise ECG', '', ''),
            t('Holter Monitoring', 'investigation', 'holter, 24-hour ECG monitoring', '', ''),
            t('USG Abdomen', 'investigation', 'ultrasound abdomen, abdominal sonography', '', ''),
            t('USG Pelvis', 'investigation', 'pelvic ultrasound, USG pelvis', '', ''),
            t('USG Thyroid', 'investigation', 'thyroid ultrasound, neck USG', '', ''),
            t('CECT Abdomen', 'investigation', 'CT abdomen with contrast, CT scan abdomen', '', ''),
            t('MRI Brain', 'investigation', 'brain MRI, cranial MRI', '', ''),
            t('MRI Spine', 'investigation', 'spine MRI, spinal MRI', '', ''),
            t('CT Scan Brain', 'investigation', 'brain CT, head CT scan', '', ''),
            t('PFT (Pulmonary Function Test)', 'investigation', 'lung function test, spirometry, PFT', '', ''),
            t('Spirometry', 'investigation', 'lung capacity test, FEV1, FVC', '', ''),
            t('Sleep Study', 'investigation', 'polysomnography, sleep apnoea test', '', ''),
            t('Colonoscopy', 'investigation', 'colon scope, large intestine endoscopy', '', ''),
            t('Upper GI Endoscopy', 'investigation', 'gastroscopy, OGD scope, upper endoscopy', '', ''),
            t('Nerve Conduction Study', 'investigation', 'NCS, nerve test, EMG NCS', '', ''),
            t('EEG', 'investigation', 'electroencephalogram, brain wave test', '', ''),
            t('Bone Mineral Density (DEXA Scan)', 'investigation', 'DEXA, bone density, osteoporosis test', '', ''),
            t('Pap Smear', 'investigation', 'cervical smear, pap test, cervical cancer screening', '', ''),
            t('Mammography', 'investigation', 'mammogram, breast X-ray, breast cancer screening', '', ''),
            t('IVP (Intravenous Pyelogram)', 'investigation', 'kidney X-ray, IVU, intravenous urogram', '', ''),
        ]

        # ── Advice ─────────────────────────────────────────────────────
        items += [
            t('Drink plenty of fluids (at least 2-3 litres per day)', 'advice', 'paani piyo, hydration, pani pina', '', ''),
            t('Avoid oily and spicy food', 'advice', 'tel masala mat khao, greasy food avoid karo', '', ''),
            t('Bed rest for 3 days', 'advice', 'rest karo, araam karo', '', ''),
            t('Salt restricted diet (less than 2g sodium/day)', 'advice', 'namak kam khao, low salt', '', ''),
            t('Low fat diet', 'advice', 'fat kam khao, less oil diet', '', ''),
            t('Diabetic diet — avoid sugar and refined carbs', 'advice', 'sugar mat khao, chini band, diabetes diet', '', ''),
            t('High fibre diet', 'advice', 'fiber diet, green vegetables, fruits', '', ''),
            t('Increase water intake', 'advice', 'zyada paani piyo, pani piyo', '', ''),
            t('Avoid alcohol completely', 'advice', 'sharaab band karo, alcohol avoid', '', ''),
            t('Avoid smoking', 'advice', 'beedi sigaret band, smoking band karo', '', ''),
            t('Regular exercise (30 min brisk walk daily)', 'advice', 'exercise karo, walk karo, yoga', '', ''),
            t('Weight reduction', 'advice', 'wajan kam karo, weight loss, motapa kam karo', '', ''),
            t('Follow up in 2 weeks', 'advice', '2 hafte baad milna, 2 weeks mein checkup', '', ''),
            t('Follow up in 1 month', 'advice', '1 mahine baad milna, 1 month follow up', '', ''),
            t('Follow up in 3 months with repeat HbA1c', 'advice', '3 mahine baad milna HbA1c ke saath', '', ''),
            t('Monitor blood pressure daily at home', 'advice', 'BP ghar par napo, BP monitor karo', '', ''),
            t('Monitor blood sugar fasting daily', 'advice', 'sugar ghar par napo, glucose check karo', '', ''),
            t('Take medicines regularly without missing', 'advice', 'dawai niyamit lo, dawai mat bhulo', '', ''),
            t('Do not stop medicines on your own', 'advice', 'dawai band mat karo, doctor se poocho', '', ''),
            t('Avoid NSAIDs (Brufen/Voveran) as they affect kidneys', 'advice', 'Brufen/Voveran mat lo, pain killer avoid', '', ''),
            t('Rest and avoid strenuous activity', 'advice', 'araam karo, kaam kam karo, heavy work avoid', '', ''),
            t('Elevate legs while sleeping', 'advice', 'pair uthake so, paon upar rakhna', '', ''),
            t('Use compression stockings', 'advice', 'compression stockings, pressure stockings', '', ''),
            t('Avoid sitting for long periods', 'advice', 'zyada mat baitho, thodi thodi der mein khade ho', '', ''),
            t('Do neck exercises as advised', 'advice', 'gardan ki kasrat, neck exercise', '', ''),
            t('Do physiotherapy as advised', 'advice', 'physio karo, physiotherapy, massage', '', ''),
            t('Ice pack application for pain', 'advice', 'ice lagao, cold compress', '', ''),
            t('Hot fomentation for muscle pain', 'advice', 'garma patti, hot water bag, senkna', '', ''),
            t('Avoid cold water and cold drinks', 'advice', 'thanda paani mat piyo, cold drinks avoid', '', ''),
            t('Steam inhalation twice a day', 'advice', 'bhap lo, steam lo, inhalation', '', ''),
            t('Gargle with warm salt water', 'advice', 'garara karo, namak wale pani se gargle', '', ''),
            t('Nasal saline drops as needed', 'advice', 'naak mein drops dalo, nasal drops', '', ''),
            t('Avoid allergens/dust', 'advice', 'dhool se door raho, allergen avoid, dust avoid', '', ''),
            t('Use sunscreen SPF 30+ daily', 'advice', 'sunscreen lagao, skin protection', '', ''),
            t('Moisturise skin twice daily', 'advice', 'moisturizer lagao, skin moisturise karo', '', ''),
            t('Do not scratch affected area', 'advice', 'khujlaio mat, rash mat khujao', '', ''),
            t('Keep wound clean and dry', 'advice', 'zakhm saaf rakhna, wound clean', '', ''),
            t('Change dressing daily', 'advice', 'patti badlo, bandage change karo', '', ''),
            t('Avoid direct sunlight on affected area', 'advice', 'dhoop se bachao, sun exposure avoid', '', ''),
            t('Oral rehydration solution (ORS) for diarrhoea', 'advice', 'ORS piyo, electral, nimbu namak pani', '', ''),
            t('BRAT diet (banana rice applesauce toast) for loose stools', 'advice', 'BRAT diet, banana rice dahi', '', ''),
            t('Avoid milk and dairy for 48 hours during diarrhoea', 'advice', 'doodh band, dairy band diarrhea mein', '', ''),
            t('Light easily digestible food', 'advice', 'halka khaana, khickhdi, dahi chawal, light diet', '', ''),
            t('Frequent small meals', 'advice', 'chhoti chhoti meal lo, thodi thodi der mein khao', '', ''),
            t('Do not lie down immediately after eating', 'advice', 'khane ke baad mat leto, upright raho', '', ''),
            t('Elevate head of bed by 6 inches', 'advice', 'sir utha ke so, elevated pillow', '', ''),
            t('Pelvic floor exercises (Kegel exercises)', 'advice', 'kegel exercise, pelvic floor', '', ''),
            t('Avoid lifting heavy weights', 'advice', 'bhari cheez mat uthao, heavy lifting avoid', '', ''),
            t('Complete full course of antibiotics', 'advice', 'antibiotic poora lo, antibiotics course complete karo', '', ''),
            t('Wear loose comfortable clothing', 'advice', 'dhila kapda pahno, comfortable clothes', '', ''),
            t('Reduce stress and practice relaxation', 'advice', 'tension mat lo, meditation karo, stress reduce karo', '', ''),
        ]

        total = len(items)
        MedicalTerm.objects.bulk_create(items, ignore_conflicts=True)

        from django.db.models import Count
        counts = MedicalTerm.objects.values('category').annotate(n=Count('id'))
        for c in counts:
            self.stdout.write(f"  {c['category']}: {c['n']}")
        self.stdout.write(self.style.SUCCESS(f'Seeded {total} medical terms.'))
