"""Seed MedicalTerm with 1300+ high-quality clinical terms for Indian GP practice."""
from django.core.management.base import BaseCommand
from prescription.models import MedicalTerm


class Command(BaseCommand):
    help = 'Seed medical terms (symptoms, diagnoses, investigations, advice, snippets, abbreviations)'

    def handle(self, *args, **options):
        if MedicalTerm.objects.count() >= 800:
            self.stdout.write('Already seeded (>= 800 terms). Skipping.')
            return

        MedicalTerm.objects.all().delete()
        items = []

        def t(term, category, aliases='', specialty='', icd_code='', weight=50):
            return MedicalTerm(
                term=term, category=category, aliases=aliases,
                specialty=specialty, icd_code=icd_code, weight=weight
            )

        # ── ABBREVIATIONS (weight 95) ───────────────────────────────────────
        items += [
            t('c/o', 'abbreviation', 'complaint of, complaining of, presenting with', weight=95),
            t('h/o', 'abbreviation', 'history of, with history of, hx of', weight=95),
            t('k/c/o', 'abbreviation', 'known case of, known patient of, known case', weight=95),
            t('O/E', 'abbreviation', 'on examination, on exam, examination findings', weight=95),
            t('p/h/o', 'abbreviation', 'past history of, previous history, past medical history', weight=95),
            t('a/w', 'abbreviation', 'associated with, along with, accompanied by', weight=95),
            t('s/o', 'abbreviation', 'suggestive of, suspicious of, s/o', weight=95),
            t('b/l', 'abbreviation', 'bilateral, both sides, bilaterally', weight=95),
            t('u/l', 'abbreviation', 'unilateral, one side', weight=95),
            t('B/L', 'abbreviation', 'bilateral, both limbs, bilateral involvement', weight=95),
            t('SOB', 'abbreviation', 'shortness of breath, breathlessness, dyspnea, dyspnoea, breathless', weight=95),
            t('DOE', 'abbreviation', 'dyspnoea on exertion, breathlessness on exertion, exertional dyspnoea', weight=95),
            t('PND', 'abbreviation', 'paroxysmal nocturnal dyspnoea, nocturnal breathlessness', weight=95),
            t('URTI', 'abbreviation', 'upper respiratory tract infection, upper RTI, sardi khansi, common cold', weight=95),
            t('LRTI', 'abbreviation', 'lower respiratory tract infection, chest infection, lower RTI', weight=95),
            t('UTI', 'abbreviation', 'urinary tract infection, peshab infection, bladder infection, peshab mein jalan', weight=95),
            t('BP', 'abbreviation', 'blood pressure, BP reading, systolic diastolic', weight=95),
            t('HR', 'abbreviation', 'heart rate, pulse rate, pulse per minute', weight=95),
            t('RR', 'abbreviation', 'respiratory rate, breathing rate, breaths per minute', weight=95),
            t('SpO2', 'abbreviation', 'oxygen saturation, pulse oximetry, oxygen level, spo2 reading', weight=95),
            t('Temp', 'abbreviation', 'temperature, body temperature, fever reading', weight=95),
            t('Wt', 'abbreviation', 'weight, body weight, patient weight', weight=95),
            t('Ht', 'abbreviation', 'height, patient height', weight=95),
            t('BMI', 'abbreviation', 'body mass index, BMI calculation', weight=95),
            t('FBS', 'abbreviation', 'fasting blood sugar, fasting glucose, sugar fasting', weight=95),
            t('PPBS', 'abbreviation', 'post-prandial blood sugar, post meal sugar, 2 hour sugar', weight=95),
            t('HbA1c', 'abbreviation', 'glycosylated haemoglobin, A1c, long term sugar, 3 month sugar', weight=95),
            t('CBC', 'abbreviation', 'complete blood count, blood test, haemogram', weight=95),
            t('LFT', 'abbreviation', 'liver function test, liver profile, liver test', weight=95),
            t('KFT', 'abbreviation', 'kidney function test, renal function test, RFT', weight=95),
            t('TFT', 'abbreviation', 'thyroid function test, thyroid profile, T3 T4 TSH', weight=95),
            t('ECG', 'abbreviation', 'electrocardiogram, heart tracing, EKG, 12 lead', weight=95),
            t('USG', 'abbreviation', 'ultrasound, sonography, ultrasonography', weight=95),
            t('CECT', 'abbreviation', 'contrast enhanced CT, CT with contrast, contrast CT', weight=90),
            t('MRI', 'abbreviation', 'magnetic resonance imaging, MRI scan', weight=90),
            t('CXR', 'abbreviation', 'chest X-ray, chest radiograph, X-ray chest', weight=95),
            t('ECHO', 'abbreviation', '2D echocardiography, echo, cardiac ultrasound', weight=90),
            t('OPD', 'abbreviation', 'outpatient department, outpatient, clinic visit', weight=90),
            t('IPD', 'abbreviation', 'inpatient department, admitted, hospitalised', weight=90),
            t('ICU', 'abbreviation', 'intensive care unit, critical care', weight=85),
            t('NICU', 'abbreviation', 'neonatal ICU, neonatal intensive care', weight=80),
            t('OT', 'abbreviation', 'operation theatre, operating room, surgery room', weight=85),
            t('ANC', 'abbreviation', 'antenatal care, antenatal checkup, pregnancy checkup', weight=90),
            t('PNC', 'abbreviation', 'postnatal care, postnatal checkup, after delivery checkup', weight=85),
            t('LSCS', 'abbreviation', 'lower segment caesarean section, C-section, caesarean', weight=90),
            t('NVD', 'abbreviation', 'normal vaginal delivery, normal delivery', weight=90),
            t('MTP', 'abbreviation', 'medical termination of pregnancy, abortion, termination', weight=85),
            t('D&C', 'abbreviation', 'dilation and curettage, dilatation and curettage', weight=85),
            t('IUGR', 'abbreviation', 'intrauterine growth restriction, growth restricted fetus', weight=80),
            t('GDM', 'abbreviation', 'gestational diabetes mellitus, diabetes in pregnancy, pregnancy sugar', weight=90),
            t('PIH', 'abbreviation', 'pregnancy induced hypertension, BP in pregnancy, gestational hypertension', weight=90),
            t('APH', 'abbreviation', 'antepartum haemorrhage, bleeding before delivery', weight=80),
            t('PPH', 'abbreviation', 'postpartum haemorrhage, bleeding after delivery', weight=80),
            t('DVT', 'abbreviation', 'deep vein thrombosis, leg clot, deep vein clot', weight=85),
            t('PE', 'abbreviation', 'pulmonary embolism, lung clot', weight=85),
            t('MI', 'abbreviation', 'myocardial infarction, heart attack, AMI', weight=95),
            t('ACS', 'abbreviation', 'acute coronary syndrome, heart attack spectrum', weight=90),
            t('NSTEMI', 'abbreviation', 'non ST elevation MI, non-STEMI', weight=85),
            t('STEMI', 'abbreviation', 'ST elevation MI, STEMI, heart attack with ST elevation', weight=85),
            t('LVF', 'abbreviation', 'left ventricular failure, left heart failure', weight=85),
            t('CCF', 'abbreviation', 'congestive cardiac failure, congestive heart failure, heart failure', weight=90),
            t('AF', 'abbreviation', 'atrial fibrillation, irregular heart beat, AFib', weight=90),
            t('VT', 'abbreviation', 'ventricular tachycardia, fast heart rhythm', weight=80),
            t('VF', 'abbreviation', 'ventricular fibrillation, cardiac arrest rhythm', weight=75),
            t('LBBB', 'abbreviation', 'left bundle branch block, ECG finding', weight=75),
            t('RBBB', 'abbreviation', 'right bundle branch block, ECG finding', weight=75),
            t('PTCA', 'abbreviation', 'percutaneous transluminal coronary angioplasty, angioplasty, stenting', weight=75),
            t('CABG', 'abbreviation', 'coronary artery bypass graft, bypass surgery, open heart surgery', weight=75),
            t('CVA', 'abbreviation', 'cerebrovascular accident, stroke, brain attack', weight=90),
            t('TIA', 'abbreviation', 'transient ischaemic attack, mini stroke, transient stroke', weight=85),
            t('GCS', 'abbreviation', 'Glasgow coma scale, consciousness score, GCS score', weight=85),
            t('MMSE', 'abbreviation', 'mini mental state examination, cognitive test', weight=75),
            t('LP', 'abbreviation', 'lumbar puncture, spinal tap, CSF analysis', weight=80),
            t('EEG', 'abbreviation', 'electroencephalogram, brain wave test, seizure test', weight=80),
            t('EMG', 'abbreviation', 'electromyogram, muscle nerve test', weight=75),
            t('NCS', 'abbreviation', 'nerve conduction study, nerve test, conduction velocity', weight=75),
            t('UGIB', 'abbreviation', 'upper GI bleed, upper gastrointestinal bleeding, haematemesis', weight=80),
            t('LGIB', 'abbreviation', 'lower GI bleed, lower gastrointestinal bleeding, rectal bleeding', weight=80),
            t('ERCP', 'abbreviation', 'endoscopic retrograde cholangiopancreatography, bile duct scope', weight=70),
            t('EGD', 'abbreviation', 'esophagogastroduodenoscopy, upper GI scope, gastroscopy', weight=75),
            t('PCNL', 'abbreviation', 'percutaneous nephrolithotomy, kidney stone surgery', weight=70),
            t('TRUS', 'abbreviation', 'transrectal ultrasound, prostate ultrasound', weight=70),
            t('PSA', 'abbreviation', 'prostate specific antigen, prostate cancer marker', weight=80),
            t('DRE', 'abbreviation', 'digital rectal examination, per rectal examination', weight=75),
            t('PAP', 'abbreviation', 'Pap smear, cervical smear, papanicolaou test', weight=80),
            t('HTN', 'abbreviation', 'hypertension, high blood pressure, BP high', weight=95),
            t('DM', 'abbreviation', 'diabetes mellitus, diabetes, sugar disease', weight=95),
            t('IHD', 'abbreviation', 'ischaemic heart disease, coronary artery disease, CAD', weight=90),
            t('CKD', 'abbreviation', 'chronic kidney disease, chronic renal failure', weight=90),
            t('COPD', 'abbreviation', 'chronic obstructive pulmonary disease, chronic bronchitis, emphysema', weight=90),
            t('TB', 'abbreviation', 'tuberculosis, kshay rog, TB disease, pulmonary TB', weight=95),
            t('NKDA', 'abbreviation', 'no known drug allergies, no drug allergy', weight=90),
            t('PR', 'abbreviation', 'per rectum, rectal examination, rectal route', weight=85),
            t('R/S', 'abbreviation', 'respiratory system, respiratory examination', weight=85),
            t('C/V', 'abbreviation', 'cardiovascular, cardiovascular system, CVS', weight=85),
            t('CNS', 'abbreviation', 'central nervous system, neurological examination', weight=85),
        ]

        # ── SNIPPETS (weight 90) ───────────────────────────────────────────
        items += [
            t('c/o fever', 'snippet',
              'fever complaint, fever history, presenting fever, c/o bukhar',
              weight=90),
            t('c/o cough cold', 'snippet',
              'cough cold complaint, upper respiratory, khansi zukam, URTI complaint',
              weight=90),
            t('c/o abdominal pain', 'snippet',
              'stomach pain complaint, pet dard complaint, abdominal complaint',
              weight=90),
            t('c/o headache', 'snippet',
              'headache complaint, sir dard complaint, cephalalgia complaint',
              weight=90),
            t('vitals', 'snippet',
              'vital signs, BP HR temp spo2, examination vitals, O/E vitals',
              weight=90),
            t('no history', 'snippet',
              'no past history, no h/o, no significant history, no comorbidities, NKDA',
              weight=90),
            t('drug allergy', 'snippet',
              'drug allergy history, NKDA, no known drug allergy, allergy history',
              weight=90),
            t('family history', 'snippet',
              'family h/o, family history of DM HTN, hereditary, family background',
              weight=90),
            t('menstrual history', 'snippet',
              'menstrual h/o, LMP cycles, period history, gynaec history',
              weight=90),
            t('obstetric history', 'snippet',
              'obstetric h/o, gravida para, G P L A, pregnancy history',
              weight=90),
            t('general examination', 'snippet',
              'G/E findings, general exam, conscious oriented cooperative, pallor icterus',
              weight=90),
            t('pallor icterus', 'snippet',
              'PICCLED, pallor icterus cyanosis clubbing lymphadenopathy oedema, systematic exam findings',
              weight=90),
            t('respiratory exam', 'snippet',
              'respiratory system examination, lung examination, R/S findings, air entry',
              weight=90),
            t('cvs exam', 'snippet',
              'cardiovascular examination, heart examination, CVS findings, S1 S2',
              weight=90),
            t('abdomen exam', 'snippet',
              'abdominal examination, per abdomen, soft non-tender, organomegaly',
              weight=90),
            t('cns exam', 'snippet',
              'CNS examination, neurological examination, focal neurological deficit, higher functions',
              weight=90),
            t('review advice', 'snippet',
              'review after, follow up advice, return if, SOS advice, symptoms worsen',
              weight=90),
            t('diet advice', 'snippet',
              'dietary advice, food advice, fluids light diet, avoid oily',
              weight=90),
            t('bp advice', 'snippet',
              'hypertension advice, BP advice, low salt exercise, blood pressure advice',
              weight=90),
            t('diabetes advice', 'snippet',
              'diabetes advice, DM advice, sugar advice, low sugar diet, HbA1c',
              weight=90),
            t('follow up', 'snippet',
              'follow up after, review after days weeks, next visit, follow-up advice',
              weight=90),
            t('investigation advice', 'snippet',
              'investigations advised, tests advised, reports to bring, lab advice',
              weight=90),
            t('referral', 'snippet',
              'referred to specialist, referral note, refer to, specialist consultation',
              weight=90),
            t('discharge advice', 'snippet',
              'discharge summary, discharged on, review on, SOS visit, discharge instructions',
              weight=90),
            t('c/o back pain', 'snippet',
              'back pain complaint, kamar dard complaint, low back pain complaint',
              weight=90),
            t('c/o chest pain', 'snippet',
              'chest pain complaint, seene mein dard, cardiac complaint',
              weight=90),
            t('c/o breathlessness', 'snippet',
              'SOB complaint, dyspnoea complaint, breathlessness complaint, sans ki takleef',
              weight=90),
            t('c/o burning urination', 'snippet',
              'dysuria complaint, UTI complaint, peshab mein jalan complaint',
              weight=90),
            t('c/o joint pain', 'snippet',
              'joint pain complaint, jodo ka dard, arthralgia complaint',
              weight=90),
            t('c/o dizziness', 'snippet',
              'vertigo complaint, chakkar complaint, dizziness history',
              weight=90),
            t('c/o vomiting diarrhoea', 'snippet',
              'gastroenteritis complaint, vomiting diarrhoea, ulti dast, AGE complaint',
              weight=90),
            t('systemic examination', 'snippet',
              'systemic exam, CVS RS CNS abdomen, all systems examination',
              weight=90),
            t('antenatal checkup', 'snippet',
              'ANC visit, antenatal visit, pregnancy checkup, obstetric examination',
              weight=90),
            t('asthma review', 'snippet',
              'asthma follow up, bronchial asthma review, inhaler compliance, wheeze',
              weight=90),
            t('diabetes review', 'snippet',
              'DM follow up, diabetes review, sugar review, HbA1c review, glycaemic control',
              weight=90),
            t('hypertension review', 'snippet',
              'HTN review, BP review, blood pressure follow up, antihypertensive review',
              weight=90),
            t('thyroid review', 'snippet',
              'thyroid follow up, hypothyroid review, TSH review, thyroxine review',
              weight=90),
        ]

        # ── SYMPTOMS (weight 70-100) ───────────────────────────────────────
        items += [
            # High weight (90-100) — seen daily
            t('Fever', 'symptom', 'bukhar, bukhaar, tez bukhar, jwar, pyrexia, hafta se bukhar, febrile', weight=100, icd_code='R50'),
            t('Cough', 'symptom', 'khansi, khaansi, sukhi khansi, balgam wali khansi, dry cough, productive cough, khasi', weight=100, icd_code='R05'),
            t('Cold', 'symptom', 'zukam, nazla, runny nose, nasal discharge, sardi, common cold', weight=95, icd_code='J00'),
            t('Sore throat', 'symptom', 'gala dard, gale mein dard, gale mein kharash, throat pain, throat irritation', weight=95, icd_code='J02.9'),
            t('Body ache', 'symptom', 'badan dard, body pain, pura badan dard, myalgia, generalised bodyache, sarv anga vedna', weight=95, icd_code='M79.1'),
            t('Headache', 'symptom', 'sir dard, sar dard, sardard, cephalalgia, sir mein dard, head pain', weight=100, icd_code='R51'),
            t('Fatigue', 'symptom', 'thakaan, kamzori, tiredness, lethargy, asthenia, exhaustion, thaka hua', weight=95, icd_code='R53'),
            t('Weakness', 'symptom', 'kamzori, taakat na hona, debility, weakness, general weakness', weight=95, icd_code='R53'),
            t('Nausea', 'symptom', 'ji machlana, matli, ulti jaisi feeling, jee machlana, nauseous', weight=95, icd_code='R11'),
            t('Vomiting', 'symptom', 'ulti, qai, vomiting, throwing up, puke', weight=95, icd_code='R11'),
            t('Diarrhoea', 'symptom', 'dast, loose motions, patlaa potty, loose stool, watery stool, latrine banana', weight=95, icd_code='R19.7'),
            t('Constipation', 'symptom', 'kabz, qabz, motions nahi, kabziyat, hard stool, pakhana nahi', weight=95, icd_code='K59.0'),
            t('Abdominal pain', 'symptom', 'pet dard, pet mein dard, pait dard, stomach pain, tummy pain, nabhi dard', weight=100, icd_code='R10'),
            t('Chest pain', 'symptom', 'seene mein dard, seene ka dard, chest mein dard, cardiac pain, angina, heart pain', weight=100, icd_code='R07'),
            t('Palpitations', 'symptom', 'dil dharakna, dil ki dhadkan, ghabrahat, tachycardia symptom, heart racing, dhadkan tez', weight=95, icd_code='R00'),
            t('Breathlessness', 'symptom', 'sans nahi aana, dam phulna, dam ghutna, dyspnoea, SOB, saans ki takleef', weight=100, icd_code='R06'),
            t('Dizziness', 'symptom', 'chakkar, sir ghoomna, vertigo, chakkar aana, giddiness', weight=95, icd_code='R42'),
            t('Back pain', 'symptom', 'kamar dard, peeth dard, kamar mein dard, low back pain, lumbar pain, spine pain', weight=100, icd_code='M54'),
            t('Joint pain', 'symptom', 'jodo ka dard, jodo mein dard, arthralgia, joint ache', weight=95, icd_code='M25.5'),
            t('Knee pain', 'symptom', 'ghutne ka dard, ghutna dard, knee ache, knee arthralgia', weight=95, icd_code='M25.56'),
            t('Rash', 'symptom', 'daane, chhale, skin rash, chehre par daane, chaale, eruption', weight=95, icd_code='R21'),
            t('Itching', 'symptom', 'khujli, jalan, kharish, pruritus, khaarish', weight=95, icd_code='L29'),
            t('Burning urination', 'symptom', 'peshab mein jalan, urination mein dard, dysuria, painful urination', weight=95, icd_code='R30.0'),
            t('Frequent urination', 'symptom', 'baar baar peshab, peshab zyada, pollakiuria, urinary frequency', weight=95, icd_code='R35'),
            t('Pedal oedema', 'symptom', 'paon sooja, paon mein sujan, pair sooja, ankle swelling, foot swelling', weight=95, icd_code='R60'),
            t('Loss of appetite', 'symptom', 'bhook na lagna, khana nahi khaana, anorexia, poor appetite', weight=95, icd_code='R63.0'),
            t('Weight loss', 'symptom', 'wajan ghatna, vajan kam hona, wajan girna', weight=95, icd_code='R63.4'),
            t('Weight gain', 'symptom', 'wajan badh gaya, motapa, weight badh gaya', weight=90, icd_code='R63.5'),
            t('Running nose', 'symptom', 'naak behna, rhinorrhoea, watery nose discharge, nasal drip', weight=95, icd_code='J00'),
            t('Blocked nose', 'symptom', 'naak band hona, nasal block, nasal congestion, band naak', weight=95, icd_code='R09.8'),
            t('Sneezing', 'symptom', 'chhink aana, frequent sneezing, sneeze', weight=90, icd_code='R06.7'),
            t('Acidity', 'symptom', 'gas, seene mein jalan, chest burning, khatta pani aana, heartburn, GERD symptom, acid reflux', weight=95, icd_code='R12'),
            t('Jaundice', 'symptom', 'piliya, peeli aankhein, peela paan, yellow discolouration, icterus', weight=90, icd_code='R17'),
            t('Excessive thirst', 'symptom', 'pyaas zyada lagna, bahut pyaas, polydipsia, excessive water intake', weight=90, icd_code='R63.1'),
            t('Hair loss', 'symptom', 'baal girna, baal jhadna, alopecia, baldness, hair fall', weight=90, icd_code='L65'),
            # Medium weight (70-85)
            t('Ear pain', 'symptom', 'kaan mein dard, otalgia, ear ache', weight=80, icd_code='H92.0'),
            t('Ear discharge', 'symptom', 'kaan behna, otorrhoea, ear pus', weight=75, icd_code='H92.1'),
            t('Tinnitus', 'symptom', 'kaan mein awaaz, ringing in ears, kaan bajnaa', weight=75, icd_code='H93.1'),
            t('Hearing loss', 'symptom', 'sunne mein takleef, sunai nahi deta, deafness, hypoacusis', weight=75, icd_code='H91'),
            t('Eye redness', 'symptom', 'aankhein laal hona, red eyes, conjunctival injection', weight=80, icd_code='H57.8'),
            t('Eye discharge', 'symptom', 'aankhon se pus, eye pus, conjunctival discharge', weight=75, icd_code='H00.1'),
            t('Watering eyes', 'symptom', 'aankhein se paani, epiphora, lacrimation, excessive tearing', weight=75, icd_code='H04.2'),
            t('Blurred vision', 'symptom', 'dhundhla dikhna, aankhon se dhundha, visual blurring, decreased vision', weight=80, icd_code='H53.8'),
            t('Double vision', 'symptom', 'do do dikhna, diplopia, double images', weight=75, icd_code='H53.2'),
            t('Mouth ulcers', 'symptom', 'muh ke chhale, aphthous ulcer, oral ulcer, chale muh mein', weight=80, icd_code='K12.0'),
            t('Dental pain', 'symptom', 'daant dard, toothache, dental ache', weight=80, icd_code='K08.8'),
            t('Difficulty swallowing', 'symptom', 'nigalne mein takleef, dysphagia, khana nigalna mein problem', weight=80, icd_code='R13'),
            t('Bloating', 'symptom', 'pet phoolna, afara, gas problem, distension', weight=85, icd_code='R14'),
            t('Flatulence', 'symptom', 'gas pasna, vayu, flatus, wind problem', weight=80, icd_code='R14.3'),
            t('Belching', 'symptom', 'dakaar, eructation, burping, belch', weight=75, icd_code='R14.2'),
            t('Haematemesis', 'symptom', 'khoon ki ulti, blood in vomit, vomiting blood, UGIB symptom', weight=80, icd_code='K92.0'),
            t('Blood in stool', 'symptom', 'potty mein khoon, haematochezia, malaena, rectal bleeding, LGIB symptom', weight=80, icd_code='K92.1'),
            t('Blood in urine', 'symptom', 'peshab mein khoon, haematuria, red urine, blood urine', weight=80, icd_code='R31'),
            t('Dark urine', 'symptom', 'kaala peshab, dark coloured urine, tea coloured urine', weight=75, icd_code='R82'),
            t('Pallor', 'symptom', 'rang safed hona, paleness, anaemic appearance, khoon ki kami dikh rahi', weight=80, icd_code='R23.1'),
            t('Excessive sweating', 'symptom', 'paseena bahut zyada, hyperhidrosis, diaphoresis, night sweats, excessive perspiration', weight=80, icd_code='R61'),
            t('Night sweats', 'symptom', 'raat ko paseena, nocturnal sweating, night perspiration', weight=80, icd_code='R61'),
            t('Chills', 'symptom', 'kaanpna, sardi lagna, kambni, rigors, chills rigors', weight=85, icd_code='R68.8'),
            t('Rigors', 'symptom', 'kaanpna with fever, shivering, malarial rigors, rigors', weight=85, icd_code='R68.8'),
            t('Dandruff', 'symptom', 'sirke chhilke, scalp flaking, seborrhoeic scalp, dandruff', weight=70, icd_code='L21'),
            t('Acne', 'symptom', 'muhaase, pimples, zits, acne spots', weight=80, icd_code='L70'),
            t('Skin peeling', 'symptom', 'twacha utarna, skin peeling, desquamation, exfoliation', weight=70, icd_code='R23.4'),
            t('Dry skin', 'symptom', 'ruki hui twacha, khushk twacha, xerosis, dry flaky skin', weight=75, icd_code='L85.3'),
            t('Numbness', 'symptom', 'sunn hona, sansanahat, hypoaesthesia, numbness tingling, paon sunn', weight=85, icd_code='R20.0'),
            t('Tingling', 'symptom', 'jhanjhanahat, pins and needles, paraesthesia, sansanahat', weight=80, icd_code='R20.2'),
            t('Burning feet', 'symptom', 'pair mein jalan, burning sensation feet, peripheral neuropathy symptom', weight=80, icd_code='R20.8'),
            t('Leg cramps', 'symptom', 'pair mein khichaav, tang dard, nocturnal cramps, muscle cramps', weight=80, icd_code='R25.2'),
            t('Muscle weakness', 'symptom', 'maaspesha kamzori, muscular weakness, proximal weakness', weight=75, icd_code='M62.8'),
            t('Difficulty walking', 'symptom', 'chalna mushkil, gait problem, walking difficulty, mobility problem', weight=75, icd_code='R26'),
            t('Tremors', 'symptom', 'haath kaampna, kaampna, shaking, trembling, resting tremor', weight=80, icd_code='R25.1'),
            t('Seizures', 'symptom', 'mirchhiyan, fits, convulsions, epileptic attack, dora parna', weight=85, icd_code='R56.8'),
            t('Confusion', 'symptom', 'ulajhan, ghabrana, disorientation, altered sensorium, confusion', weight=80, icd_code='R41.0'),
            t('Memory loss', 'symptom', 'yaad na rehna, bhoolna, amnesia, forgetfulness, dementia symptom', weight=75, icd_code='R41.3'),
            t('Mood changes', 'symptom', 'mood badalna, mood swings, irritability, emotional lability', weight=75, icd_code='R45.8'),
            t('Anxiety', 'symptom', 'chinta, ghabrahat, anxious, nervousness, tension', weight=85, icd_code='F41.1'),
            t('Insomnia', 'symptom', 'neend na aana, neend ki kami, sleep disturbance, nind nahi aati', weight=85, icd_code='G47.0'),
            t('Depression', 'symptom', 'udaasi, depression, sadness, low mood, depressed', weight=80, icd_code='F32'),
            t('Irregular periods', 'symptom', 'periods irregular, machalik cycles, irregular menstruation, cycle problem', weight=85, icd_code='N92'),
            t('Heavy periods', 'symptom', 'zyada khoon, heavy menstrual bleeding, HMB, menorrhagia', weight=85, icd_code='N92.0'),
            t('Missed period', 'symptom', 'period nahi aaya, missed menstruation, amenorrhoea, period band', weight=85, icd_code='N91'),
            t('Vaginal discharge', 'symptom', 'safed pani, white discharge, leucorrhoea, vaginal discharge', weight=85, icd_code='N89.8'),
            t('Pelvic pain', 'symptom', 'pelvic dard, lower abdominal pain, pait ke neeche dard', weight=80, icd_code='R10.2'),
            t('Breast lump', 'symptom', 'chhaati mein ganth, breast mass, breast nodule', weight=80, icd_code='N63'),
            t('Breast pain', 'symptom', 'chhaati mein dard, mastalgia, breast tenderness', weight=75, icd_code='N64.4'),
            t('Nipple discharge', 'symptom', 'nipple se discharge, galactorrhoea, nipple fluid', weight=70, icd_code='N64.5'),
            t('Testicular pain', 'symptom', 'anda dard, scrotal pain, testicular ache', weight=75, icd_code='N50.8'),
            t('Testicular swelling', 'symptom', 'anda sooja, scrotal swelling, testicular mass', weight=75, icd_code='N50.8'),
            t('Reduced urine output', 'symptom', 'peshab kam aana, oliguria, low urine, kum peshab', weight=80, icd_code='R34'),
            t('Frothy urine', 'symptom', 'jhaag wala peshab, proteinuria symptom, frothy urine', weight=75, icd_code='R82.9'),
            t('Shoulder pain', 'symptom', 'kandhe ka dard, shoulder ache, rotator cuff pain', weight=80, icd_code='M75'),
            t('Hip pain', 'symptom', 'kadhe ka dard, hip ache, hip joint pain, haunch pain', weight=80, icd_code='M25.55'),
            t('Wrist pain', 'symptom', 'kalai dard, wrist ache, carpal pain', weight=75, icd_code='M25.53'),
            t('Elbow pain', 'symptom', 'koohni dard, elbow ache, lateral epicondyle pain', weight=75, icd_code='M25.52'),
            t('Finger swelling', 'symptom', 'ungli sooji, finger puffiness, dactylitis', weight=70, icd_code='M25.57'),
            t('Morning stiffness', 'symptom', 'subah akadna, morning joint stiffness, early morning stiffness', weight=80, icd_code='M25.6'),
            t('Jaw pain', 'symptom', 'jabbde ka dard, jaw ache, TMJ pain, temporomandibular pain', weight=70, icd_code='M26.6'),
            t('Neck stiffness', 'symptom', 'gardan akdi, nuchal rigidity, stiff neck, meningeal sign', weight=80, icd_code='R29.1'),
            t('Facial pain', 'symptom', 'chehra dard, face pain, trigeminal neuralgia symptom', weight=70, icd_code='G50.0'),
            t('Nasal polyps', 'symptom', 'naak mein ghilaf, nasal polyp symptom, blocked nose polyp', weight=70, icd_code='J33'),
            t('Post-nasal drip', 'symptom', 'naak se gale mein girar, postnasal drip, throat irritation from nose', weight=70, icd_code='J30.9'),
            t('Tonsil enlargement', 'symptom', 'tonsil sooja, tonsillar enlargement, tonsil bada', weight=75, icd_code='J35.1'),
            t('Pleuritic chest pain', 'symptom', 'saans mein dard, pleurisy pain, chest pain on breathing', weight=75, icd_code='R07.1'),
            t('Wheezing', 'symptom', 'saansein ki awaaz, wheeze, asthmatic wheeze, siti ki awaaz', weight=85, icd_code='R06.2'),
            t('Hemoptysis', 'symptom', 'khansi mein khoon, blood in cough, coughing blood', weight=80, icd_code='R04.2'),
            t('Vertigo', 'symptom', 'sab ghoomna, room spinning, chakkar vertigo, BPPV symptom', weight=85, icd_code='R42'),
            t('Calf swelling', 'symptom', 'paind sooja, calf oedema, DVT symptom', weight=75, icd_code='R60'),
            t('Calf pain', 'symptom', 'paind dard, calf muscle pain, DVT pain, leg pain', weight=75, icd_code='M79.1'),
            t('Ankle swelling', 'symptom', 'ankle sooja, ankle oedema, periankle swelling', weight=80, icd_code='R60'),
            t('Low back pain', 'symptom', 'kamar dard, lumbar pain, kamar neeche dard, lumbago', weight=100, icd_code='M54.5'),
            t('Neck pain', 'symptom', 'gardan dard, cervicalgia, neck ache, cervical pain', weight=85, icd_code='M54.2'),
            t('Painful periods', 'symptom', 'masik mein dard, period mein dard, dysmenorrhoea, crampy periods', weight=85, icd_code='N94.4'),
            t('Excessive hunger', 'symptom', 'bahut bhook, polyphagia, hunger increase, bhook zyada lagna', weight=75, icd_code='R63.2'),
            t('Skin darkening', 'symptom', 'twacha kala hona, hyperpigmentation, skin discolouration', weight=70, icd_code='L81'),
            t('Throat congestion', 'symptom', 'gale mein kharash, throat irritation, pharyngeal congestion', weight=80, icd_code='J02.9'),
            t('Chest tightness', 'symptom', 'seene mein akaspan, chest tightness, constriction chest', weight=85, icd_code='R07.9'),
            t('High blood pressure', 'symptom', 'BP high, blood pressure high, hypertension symptom', weight=95, icd_code='I10'),
        ]

        # ── DIAGNOSES (weight 50-100) ──────────────────────────────────────
        items += [
            # Very common (95-100)
            t('Viral fever', 'diagnosis', 'viral bukhar, viral infection fever, pyrexia of unknown origin', weight=100, icd_code='A99'),
            t('URTI', 'diagnosis', 'upper respiratory tract infection, common cold, nazla zukam, sardi khansi', weight=100, icd_code='J06.9'),
            t('Acute pharyngitis', 'diagnosis', 'throat infection, sore throat infection, pharyngeal infection, gala kharab', weight=95, icd_code='J02.9'),
            t('Acute tonsillitis', 'diagnosis', 'tonsil infection, tonsillitis, tonsil problem, gale ke tonsil', weight=95, icd_code='J03.9'),
            t('Acute bronchitis', 'diagnosis', 'bronchitis, chest infection, lower RTI, khansi chest', weight=90, icd_code='J20.9'),
            t('Community-acquired pneumonia', 'diagnosis', 'CAP, pneumonia, lung infection, niwmonia, chest pneumonia', weight=90, icd_code='J18.9'),
            t('Influenza', 'diagnosis', 'flu, influenza virus, seasonal flu, swine flu', weight=90, icd_code='J11'),
            t('COVID-19', 'diagnosis', 'covid, corona, coronavirus, SARS-CoV-2, covid infection', weight=95, icd_code='U07.1'),
            t('COVID-19 (mild)', 'diagnosis', 'mild covid, mild corona, covid without pneumonia', weight=90, icd_code='U07.1'),
            t('COVID-19 (moderate)', 'diagnosis', 'moderate covid, covid with pneumonia, moderate corona', weight=85, icd_code='U07.1'),
            t('Dengue fever', 'diagnosis', 'dengue, dengue bukhar, dengue ka bukhar, platelet low, dengue hemorrhagic', weight=95, icd_code='A97.0'),
            t('Malaria (Plasmodium vivax)', 'diagnosis', 'malaria, vivax malaria, benign tertian malaria, P. vivax, malarial fever', weight=95, icd_code='B51'),
            t('Malaria (P. falciparum)', 'diagnosis', 'falciparum malaria, severe malaria, P. falciparum, cerebral malaria', weight=90, icd_code='B50'),
            t('Typhoid fever', 'diagnosis', 'typhoid, enteric fever, typhoid bukhar, paratyphoid, Salmonella typhi', weight=95, icd_code='A01.0'),
            t('Gastroenteritis', 'diagnosis', 'AGE, acute gastroenteritis, vomiting diarrhoea, stomach bug, food poisoning, ulti dast', weight=95, icd_code='A09'),
            t('Acute gastritis', 'diagnosis', 'gastritis, stomach inflammation, gastric inflammation', weight=90, icd_code='K29.1'),
            t('GERD', 'diagnosis', 'acid reflux, gastroesophageal reflux, heartburn disease, acidity, seene mein jalan', weight=95, icd_code='K21.0'),
            t('Peptic ulcer disease', 'diagnosis', 'peptic ulcer, stomach ulcer, gastric ulcer, duodenal ulcer, PUD', weight=90, icd_code='K27.9'),
            t('Irritable bowel syndrome', 'diagnosis', 'IBS, stomach problem, bowel syndrome, spastic colon', weight=85, icd_code='K58.9'),
            t('Functional dyspepsia', 'diagnosis', 'dyspepsia, indigestion, non-ulcer dyspepsia, gas problem, afara', weight=90, icd_code='K30'),
            t('Hypertension (essential)', 'diagnosis', 'HTN, essential hypertension, BP high, high BP, blood pressure high, uchh raktchaap, hypertension', weight=100, icd_code='I10'),
            t('Type 2 Diabetes Mellitus', 'diagnosis', 'DM2, T2DM, sugar, diabetes, madhumeh, sugar ki bimari, uncontrolled sugar, type 2 diabetes', weight=100, icd_code='E11'),
            t('Hypothyroidism', 'diagnosis', 'thyroid, low thyroid, thyroid kam, TSH high, hypothyroid, underactive thyroid', weight=95, icd_code='E03.9'),
            t('Iron deficiency anaemia', 'diagnosis', 'IDA, khoon ki kami, anaemia, anemia, hemoglobin low, Hb low, iron deficiency', weight=95, icd_code='D50.9'),
            t('Vitamin D deficiency', 'diagnosis', 'vitamin D low, D deficiency, osteomalacia, rickets, vit D', weight=90, icd_code='E55.9'),
            t('Vitamin B12 deficiency', 'diagnosis', 'B12 deficiency, cobalamin deficiency, megaloblastic anaemia, vit B12 low', weight=90, icd_code='E53.8'),
            t('UTI (uncomplicated)', 'diagnosis', 'urinary tract infection, UTI, peshab mein jalan infection, bladder infection, cystitis', weight=95, icd_code='N39.0'),
            t('Migraine', 'diagnosis', 'aadha sir dard, sir mein dard, throbbing headache, hemicranial headache, migrain', weight=95, icd_code='G43.9'),
            t('Tension headache', 'diagnosis', 'tension type headache, stress headache, band like headache', weight=90, icd_code='G44.2'),
            t('Low back pain (mechanical)', 'diagnosis', 'kamar dard, mechanical LBP, lumbago, non-specific back pain, lumbar strain', weight=100, icd_code='M54.5'),
            t('Osteoarthritis (knee)', 'diagnosis', 'OA knee, knee arthritis, ghutna arthritis, degenerative knee, knee joint degeneration', weight=95, icd_code='M17.9'),
            t('Allergic rhinitis', 'diagnosis', 'nasal allergy, hay fever, allergic nose, sneezing allergy, rhinitis', weight=90, icd_code='J30.1'),
            t('Bronchial asthma', 'diagnosis', 'asthma, daama, asthmatic attack, wheeze, bronchospasm, asthmatic bronchitis', weight=95, icd_code='J45.9'),
            t('Eczema / Atopic dermatitis', 'diagnosis', 'eczema, atopic dermatitis, atopic eczema, skin allergy eczema, kharish', weight=90, icd_code='L20.9'),
            t('Fungal infection (tinea)', 'diagnosis', 'ringworm, tinea, daad, tinea corporis, tinea cruris, fungal rash, jock itch', weight=95, icd_code='B35.9'),
            t('Scabies', 'diagnosis', 'khujli bimari, itch mite, scabies rash, sarcoptes, khujli', weight=90, icd_code='B86'),
            t('Urticaria', 'diagnosis', 'hives, allergic rash, pitti, urticaria, hives allergy', weight=90, icd_code='L50.9'),
            t('Acne vulgaris', 'diagnosis', 'acne, pimples, muhaase, facial acne, comedones', weight=90, icd_code='L70.0'),
            t('Conjunctivitis', 'diagnosis', 'eye infection, pink eye, red eye, conjunctival infection, aankhein laal', weight=90, icd_code='H10.9'),
            t('Anxiety disorder', 'diagnosis', 'anxiety, GAD, generalised anxiety, ghabrahat bimari', weight=85, icd_code='F41.1'),
            t('Depression', 'diagnosis', 'depresion, major depressive disorder, MDD, sadness, clinical depression, udaasi', weight=85, icd_code='F32.9'),
            # Common (75-90)
            t('Type 1 Diabetes Mellitus', 'diagnosis', 'T1DM, juvenile diabetes, insulin-dependent diabetes, type 1 diabetes', weight=80, icd_code='E10'),
            t('Hyperthyroidism', 'diagnosis', 'thyroid zyada, overactive thyroid, thyrotoxicosis, Graves disease, TSH low', weight=85, icd_code='E05.9'),
            t('Thyroid nodule', 'diagnosis', 'thyroid nodule, thyroid swelling, goitre, thyroid lump', weight=80, icd_code='E04.1'),
            t('PCOD / PCOS', 'diagnosis', 'PCOS, polycystic ovary, periods irregular, ovary cyst, polycystic ovarian disease', weight=90, icd_code='E28.2'),
            t('GDM (gestational diabetes)', 'diagnosis', 'GDM, diabetes in pregnancy, sugar in pregnancy, pregnancy sugar', weight=90, icd_code='O24.4'),
            t('Preeclampsia', 'diagnosis', 'PIH, hypertension in pregnancy, pregnancy induced hypertension, BP in pregnancy', weight=85, icd_code='O14.0'),
            t('Iron deficiency anaemia in pregnancy', 'diagnosis', 'anaemia pregnancy, iron deficiency pregnancy, Hb low pregnancy', weight=85, icd_code='O99.0'),
            t('Anaemia of chronic disease', 'diagnosis', 'ACD, chronic disease anaemia, secondary anaemia', weight=75, icd_code='D63.8'),
            t('CKD (chronic kidney disease)', 'diagnosis', 'CKD, chronic renal failure, kidney failure chronic, gursye fail', weight=90, icd_code='N18.9'),
            t('Nephrotic syndrome', 'diagnosis', 'nephrosis, heavy proteinuria, kidney protein loss', weight=75, icd_code='N04.9'),
            t('Renal calculus', 'diagnosis', 'kidney stone, gursye ki pathri, pathri, urinary stone, nephrolithiasis', weight=90, icd_code='N20.0'),
            t('Pyelonephritis', 'diagnosis', 'kidney infection, gurdey ki infection, upper UTI, pyelitis', weight=85, icd_code='N12'),
            t('Benign prostatic hyperplasia', 'diagnosis', 'BPH, prostate enlargement, enlarged prostate, prostate problem', weight=85, icd_code='N40'),
            t('Erectile dysfunction', 'diagnosis', 'ED, sexual dysfunction, mardaana kamzori, impotence', weight=80, icd_code='N52.9'),
            t('Ischemic heart disease', 'diagnosis', 'IHD, CAD, coronary artery disease, heart disease, ischemic heart', weight=90, icd_code='I25.9'),
            t('Stable angina', 'diagnosis', 'angina, stable CAD, exertional chest pain, angina pectoris', weight=85, icd_code='I20.8'),
            t('Unstable angina', 'diagnosis', 'ACS, unstable angina, rest angina, crescendo angina', weight=85, icd_code='I20.0'),
            t('NSTEMI', 'diagnosis', 'non-STEMI, NSTEMI, non ST elevation MI, partial heart attack', weight=80, icd_code='I21.4'),
            t('STEMI', 'diagnosis', 'ST elevation MI, STEMI, heart attack, massive MI', weight=80, icd_code='I21.3'),
            t('Heart failure', 'diagnosis', 'CCF, congestive heart failure, cardiac failure, LVF, heart failure', weight=85, icd_code='I50.9'),
            t('Atrial fibrillation', 'diagnosis', 'AF, AFib, atrial fibrillation, irregular heart beat', weight=85, icd_code='I48'),
            t('Hypertensive emergency', 'diagnosis', 'hypertensive crisis, very high BP, malignant hypertension', weight=80, icd_code='I16'),
            t('Hyperlipidaemia', 'diagnosis', 'high cholesterol, dyslipidaemia, lipid problem, cholesterol high', weight=90, icd_code='E78.5'),
            t('Metabolic syndrome', 'diagnosis', 'insulin resistance syndrome, syndrome X, metabolic disorder', weight=80, icd_code='E88.81'),
            t('Non-alcoholic fatty liver disease', 'diagnosis', 'NAFLD, fatty liver, liver mein fat, steatohepatitis', weight=85, icd_code='K76.0'),
            t('Alcoholic liver disease', 'diagnosis', 'alcoholic hepatitis, alcohol liver, cirrhosis alcoholic', weight=80, icd_code='K70.9'),
            t('Chronic hepatitis B', 'diagnosis', 'HBV, hepatitis B chronic, HBsAg positive, hepatitis B carrier', weight=85, icd_code='B18.1'),
            t('Chronic hepatitis C', 'diagnosis', 'HCV, hepatitis C chronic, anti-HCV positive', weight=80, icd_code='B18.2'),
            t('Hepatitis A', 'diagnosis', 'HAV, hepatitis A, infectious hepatitis, jaundice hepatitis A', weight=85, icd_code='B15.9'),
            t('Cirrhosis of liver', 'diagnosis', 'liver cirrhosis, liver fibrosis, end stage liver disease', weight=80, icd_code='K74.6'),
            t('Cholelithiasis', 'diagnosis', 'gallstones, pitt ki pathri, gall bladder stone, biliary calculus', weight=85, icd_code='K80.2'),
            t('Acute cholecystitis', 'diagnosis', 'gallbladder infection, cholecystitis, pitt ki thali ka dard', weight=80, icd_code='K81.0'),
            t('Haemorrhoids', 'diagnosis', 'piles, bawaaseer, anal piles, haemorrhoids, anal hemorrhoids', weight=90, icd_code='K64.9'),
            t('Anal fissure', 'diagnosis', 'anus dard, anal crack, fissure in ano, painful defecation', weight=80, icd_code='K60.0'),
            t('Hernia (inguinal)', 'diagnosis', 'inguinal hernia, kuch nikaala, hernia, groin hernia, intestinal hernia', weight=85, icd_code='K40.9'),
            t('Cellulitis', 'diagnosis', 'skin infection, bacterial skin infection, cellulitis, skin redness spreading', weight=85, icd_code='L03.9'),
            t('Abscess (skin)', 'diagnosis', 'skin abscess, boil, furuncle, abscess, pus collection skin', weight=85, icd_code='L02.9'),
            t('Impetigo', 'diagnosis', 'impetigo, crusty skin infection, bacterial skin, golden crust', weight=80, icd_code='L01.0'),
            t('Herpes zoster', 'diagnosis', 'shingles, chickenpox reactivation, belt rose, herpes zoster, zoster', weight=85, icd_code='B02.9'),
            t('Chickenpox (varicella)', 'diagnosis', 'varicella, maata, chechak, chickenpox', weight=85, icd_code='B01.9'),
            t('Dengue with thrombocytopenia', 'diagnosis', 'dengue low platelets, dengue hemorrhagic fever, severe dengue', weight=85, icd_code='A97.1'),
            t('Leptospirosis', 'diagnosis', 'leptospira, rat fever, Weil disease, leptospirosis', weight=80, icd_code='A27.9'),
            t('Chikungunya', 'diagnosis', 'chikungunya fever, chiku fever, joint pain fever, chikungunya arthritis', weight=85, icd_code='A92.0'),
            t('Pulmonary tuberculosis', 'diagnosis', 'PTB, pulmonary TB, tuberculosis lungs, lung TB, kshay rog', weight=90, icd_code='A15.0'),
            t('Extrapulmonary TB', 'diagnosis', 'TB other than lungs, extra pulmonary tuberculosis', weight=80, icd_code='A19.9'),
            t('Latent TB', 'diagnosis', 'LTBI, latent tuberculosis, latent TB infection, positive Mantoux', weight=75, icd_code='Z22.7'),
            t('COPD', 'diagnosis', 'chronic obstructive pulmonary disease, chronic bronchitis, emphysema, COPD', weight=90, icd_code='J44.9'),
            t('Bronchiectasis', 'diagnosis', 'bronchiectasis, dilated bronchi, chronic lung infection', weight=75, icd_code='J47'),
            t('Pleural effusion', 'diagnosis', 'fluid in chest, pleural fluid, chest fluid, hydrothorax', weight=80, icd_code='J90'),
            t('Pneumothorax', 'diagnosis', 'air in chest, collapsed lung, pneumothorax', weight=75, icd_code='J93.9'),
            t('Obstructive sleep apnoea', 'diagnosis', 'OSA, sleep apnoea, snoring problem, CPAP needed, sleep disordered breathing', weight=80, icd_code='G47.3'),
            t('Epilepsy', 'diagnosis', 'epilepsy, fits, seizure disorder, mirchhiyan, convulsion disorder', weight=85, icd_code='G40.9'),
            t('Febrile seizures', 'diagnosis', 'febrile convulsion, fever fits, bukhar ke dore, febrile fits', weight=85, icd_code='R56.0'),
            t('CVA (ischaemic stroke)', 'diagnosis', 'stroke, brain attack, ischaemic stroke, cerebrovascular accident', weight=85, icd_code='I63.9'),
            t('TIA', 'diagnosis', 'mini stroke, transient ischaemic attack, TIA, temporary stroke', weight=80, icd_code='G45.9'),
            t('Parkinson disease', 'diagnosis', "Parkinson's, Parkinsonism, tremor disease, resting tremor", weight=75, icd_code='G20'),
            t('Migraine with aura', 'diagnosis', 'classic migraine, migraine with visual aura, complicated migraine', weight=80, icd_code='G43.1'),
            t('Cluster headache', 'diagnosis', 'cluster headache, severe one-sided headache, periorbital headache', weight=70, icd_code='G44.0'),
            t('Cervical spondylosis', 'diagnosis', 'cervical, gardan ki haddi, neck spondylosis, cervical degenerative, neck pain disc', weight=90, icd_code='M47.812'),
            t('Lumbar spondylosis', 'diagnosis', 'lumber spondylosis, kamar ki haddi, degenerative spine, lumbar disc', weight=90, icd_code='M47.816'),
            t('Sciatica', 'diagnosis', 'sciatic nerve pain, leg pain from spine, scitica, radiculopathy L4 L5', weight=90, icd_code='M54.4'),
            t('Carpal tunnel syndrome', 'diagnosis', 'CTS, wrist nerve compression, hand numbness CTS, median nerve compression', weight=80, icd_code='G56.0'),
            t('Peripheral neuropathy', 'diagnosis', 'neuropathy, nerve damage, peripheral nerve disease, numbness tingling diagnosis', weight=80, icd_code='G62.9'),
            t('Diabetic neuropathy', 'diagnosis', 'diabetes nerve damage, diabetic peripheral neuropathy, burning feet diabetes', weight=85, icd_code='E11.40'),
            t('Rheumatoid arthritis', 'diagnosis', 'RA, inflammatory arthritis, joint inflammation, symmetrical arthritis', weight=85, icd_code='M05.9'),
            t('Gout', 'diagnosis', 'uric acid arthritis, gouty arthritis, podagra, big toe pain gout', weight=85, icd_code='M10.9'),
            t('Pseudogout', 'diagnosis', 'CPPD, calcium pyrophosphate, pseudogout', weight=60, icd_code='M11.2'),
            t('Ankylosing spondylitis', 'diagnosis', 'AS, axial spondylarthropathy, inflammatory back pain', weight=75, icd_code='M45'),
            t('Psoriatic arthritis', 'diagnosis', 'psoriasis with arthritis, PsA', weight=70, icd_code='L40.5'),
            t('Fibromyalgia', 'diagnosis', 'fibromyalgia, chronic pain syndrome, widespread pain', weight=75, icd_code='M79.7'),
            t('Osteoporosis', 'diagnosis', 'bone density loss, haddi kamzor, osteoporosis, fragility fracture', weight=80, icd_code='M81.0'),
            t('Rotator cuff tendinitis', 'diagnosis', 'rotator cuff, shoulder tendinitis, impingement syndrome', weight=75, icd_code='M75.1'),
            t('Tennis elbow', 'diagnosis', 'lateral epicondylitis, tennis elbow, elbow tendinitis', weight=75, icd_code='M77.1'),
            t('Frozen shoulder', 'diagnosis', 'adhesive capsulitis, frozen shoulder, shoulder stiffness', weight=80, icd_code='M75.0'),
            t('Plantar fasciitis', 'diagnosis', 'heel pain, plantar fasciitis, heel spur, foot pain morning', weight=80, icd_code='M72.2'),
            t('Uterine fibroid', 'diagnosis', 'fibroid, uterine leiomyoma, fibroid uterus, rasoli', weight=85, icd_code='D25.9'),
            t('Ovarian cyst', 'diagnosis', 'ovary cyst, ovarian follicular cyst, functional cyst', weight=85, icd_code='N83.2'),
            t('Endometriosis', 'diagnosis', 'endometriosis, painful periods with endometriosis', weight=75, icd_code='N80.9'),
            t('PID (pelvic inflammatory disease)', 'diagnosis', 'PID, pelvic infection, salpingitis, oophoritis', weight=80, icd_code='N73.9'),
            t('Dysmenorrhoea', 'diagnosis', 'painful periods, period pain, menstrual cramps, masik dard', weight=85, icd_code='N94.4'),
            t('Premenstrual syndrome', 'diagnosis', 'PMS, premenstrual, period mood changes', weight=75, icd_code='N94.3'),
            t('Perimenopause', 'diagnosis', 'menopause, perimenopause, climacteric, hot flashes menopause', weight=80, icd_code='N95.1'),
            t('Vaginal candidiasis', 'diagnosis', 'vaginal thrush, candida infection, fungal vaginal infection, safed pani fungal', weight=85, icd_code='B37.3'),
            t('Bacterial vaginosis', 'diagnosis', 'BV, gardnerella, vaginal bacterial infection', weight=80, icd_code='N76.0'),
            t('Psoriasis', 'diagnosis', 'psoriasis, scaly skin disease, psoriatic plaques', weight=80, icd_code='L40.9'),
            t('Seborrhoeic dermatitis', 'diagnosis', 'seborrhoeic eczema, dandruff disease, scalp dermatitis', weight=75, icd_code='L21.9'),
            t('Rosacea', 'diagnosis', 'facial redness, rosacea, facial flushing', weight=70, icd_code='L71.9'),
            t('Vitiligo', 'diagnosis', 'vitiligo, skin depigmentation, white patches, safed daag', weight=80, icd_code='L80'),
            t('Melasma', 'diagnosis', 'melasma, chloasma, facial pigmentation, pregnancy mask', weight=75, icd_code='L81.1'),
            t('Contact dermatitis', 'diagnosis', 'skin allergy, contact rash, allergic contact dermatitis', weight=80, icd_code='L25.9'),
            t('Drug reaction', 'diagnosis', 'drug rash, medication reaction, DRESS, drug eruption', weight=80, icd_code='L27.0'),
            t('Urticaria (chronic)', 'diagnosis', 'chronic hives, chronic urticaria, CU, idiopathic urticaria', weight=80, icd_code='L50.1'),
            t('Alopecia areata', 'diagnosis', 'patchy hair loss, alopecia, hair loss patches', weight=75, icd_code='L63.9'),
            t('Androgenic alopecia', 'diagnosis', 'male pattern baldness, female pattern hair loss, androgenic hair loss', weight=75, icd_code='L64'),
            t('Glaucoma', 'diagnosis', 'glaucoma, eye pressure high, IOP raised, optic nerve damage', weight=75, icd_code='H40.9'),
            t('Cataract', 'diagnosis', 'cataract, motiabind, lens opacity, cloudy lens', weight=80, icd_code='H26.9'),
            t('Diabetic retinopathy', 'diagnosis', 'diabetes eye, DR, retinal changes diabetes', weight=80, icd_code='E11.31'),
            t('Hypertensive retinopathy', 'diagnosis', 'BP eye changes, hypertensive eye, retinopathy HTN', weight=75, icd_code='H35.0'),
            t('Acute otitis media', 'diagnosis', 'ear infection, AOM, kaan ka infection, middle ear infection', weight=85, icd_code='H66.9'),
            t('Chronic suppurative otitis media', 'diagnosis', 'CSOM, chronic ear infection, running ear, kaan behna', weight=80, icd_code='H66.3'),
            t('Otitis externa', 'diagnosis', 'ear canal infection, swimmer ear, outer ear infection', weight=75, icd_code='H60.9'),
            t('BPPV', 'diagnosis', 'benign paroxysmal positional vertigo, positional vertigo, BPPV, chakkar on turning', weight=80, icd_code='H81.1'),
            t("Meniere's disease", 'diagnosis', 'Meniere, endolymphatic hydrops, vertigo hearing loss tinnitus', weight=70, icd_code='H81.0'),
            t('Acute sinusitis', 'diagnosis', 'sinusitis, sinus infection, nasal sinus, sinus headache', weight=85, icd_code='J01.9'),
            t('Chronic sinusitis', 'diagnosis', 'chronic sinus, persistent sinusitis, sinus problem', weight=80, icd_code='J32.9'),
            t('Deviated nasal septum', 'diagnosis', 'DNS, deviated septum, nasal septum deviation', weight=75, icd_code='J34.2'),
            t('Aphthous stomatitis', 'diagnosis', 'mouth ulcer, aphthous ulcer, oral ulcer, canker sore, muh mein chhale', weight=85, icd_code='K12.0'),
            t('Angular cheilitis', 'diagnosis', 'angular stomatitis, corner mouth crack, cheilitis', weight=70, icd_code='K13.0'),
            t('Appendicitis', 'diagnosis', 'appendix, appendix mein dard, right lower quadrant pain, appendiceal', weight=85, icd_code='K37'),
            # Specialist (50-70)
            t('Multiple sclerosis', 'diagnosis', 'MS, demyelinating disease, sclerosis multiple', weight=60, icd_code='G35'),
            t('Motor neuron disease', 'diagnosis', 'MND, ALS, amyotrophic lateral sclerosis, motor neurone disease', weight=55, icd_code='G12.2'),
            t('Guillain-Barre syndrome', 'diagnosis', 'GBS, ascending paralysis, acute polyneuropathy', weight=60, icd_code='G61.0'),
            t('Myasthenia gravis', 'diagnosis', 'myasthenia, neuromuscular junction disease, ptosis weakness', weight=60, icd_code='G70.0'),
            t('Systemic lupus erythematosus', 'diagnosis', 'SLE, lupus, butterfly rash, autoimmune multi-system', weight=65, icd_code='M32.9'),
            t('Vasculitis', 'diagnosis', 'vasculitis, blood vessel inflammation, systemic vasculitis', weight=60, icd_code='M31.9'),
            t('Scleroderma', 'diagnosis', 'systemic sclerosis, scleroderma, SSc, skin hardening disease', weight=55, icd_code='M34.9'),
            t("Sjogren's syndrome", 'diagnosis', 'Sjogren, dry eyes dry mouth, primary Sjogren, SS', weight=60, icd_code='M35.0'),
            t('Antiphospholipid syndrome', 'diagnosis', 'APS, antiphospholipid antibody, clotting disorder autoimmune', weight=60, icd_code='D68.6'),
            t('Sarcoidosis', 'diagnosis', 'sarcoid, sarcoidosis, granulomatous disease', weight=60, icd_code='D86.9'),
            t('ITP', 'diagnosis', 'immune thrombocytopenic purpura, ITP, platelet low autoimmune', weight=65, icd_code='D69.3'),
            t('Multiple myeloma', 'diagnosis', 'myeloma, plasma cell cancer, bone marrow cancer, MM', weight=60, icd_code='C90.0'),
            t("Hodgkin's lymphoma", 'diagnosis', 'Hodgkin lymphoma, HL, Reed-Sternberg cell lymphoma', weight=60, icd_code='C81.9'),
            t("Non-Hodgkin's lymphoma", 'diagnosis', 'NHL, non-Hodgkin, B-cell lymphoma, T-cell lymphoma', weight=60, icd_code='C85.9'),
            t('AML (leukaemia)', 'diagnosis', 'acute myeloid leukaemia, AML, blood cancer acute', weight=60, icd_code='C92.0'),
            t('CML (leukaemia)', 'diagnosis', 'chronic myeloid leukaemia, CML, Philadelphia chromosome', weight=60, icd_code='C92.1'),
            t('ALL (leukaemia)', 'diagnosis', 'acute lymphocytic leukaemia, ALL, childhood leukaemia', weight=60, icd_code='C91.0'),
            t('CLL (leukaemia)', 'diagnosis', 'chronic lymphocytic leukaemia, CLL', weight=55, icd_code='C91.1'),
            t('Breast cancer', 'diagnosis', 'breast malignancy, breast carcinoma, Ca breast, breast tumour', weight=65, icd_code='C50.9'),
            t('Cervical cancer', 'diagnosis', 'Ca cervix, cervical malignancy, cervical carcinoma', weight=65, icd_code='C53.9'),
            t('Ovarian cancer', 'diagnosis', 'Ca ovary, ovarian malignancy, ovarian carcinoma', weight=60, icd_code='C56'),
            t('Colorectal cancer', 'diagnosis', 'Ca colon, Ca rectum, colorectal carcinoma, bowel cancer', weight=60, icd_code='C20'),
            t('Hepatocellular carcinoma', 'diagnosis', 'HCC, liver cancer, hepatoma, Ca liver', weight=60, icd_code='C22.0'),
            t('Lung cancer', 'diagnosis', 'Ca lung, lung malignancy, bronchogenic carcinoma, lung tumour', weight=60, icd_code='C34.9'),
            t('Prostate cancer', 'diagnosis', 'Ca prostate, prostate malignancy, prostatic carcinoma', weight=60, icd_code='C61'),
            t('Gastric cancer', 'diagnosis', 'Ca stomach, gastric malignancy, stomach cancer', weight=60, icd_code='C16.9'),
            t("Cushing's syndrome", 'diagnosis', 'hypercortisolism, Cushing, cortisol excess', weight=60, icd_code='E24.9'),
            t("Addison's disease", 'diagnosis', 'adrenal insufficiency, Addison, cortisol deficiency', weight=60, icd_code='E27.1'),
            t('Primary aldosteronism', 'diagnosis', "Conn's syndrome, primary hyperaldosteronism, adrenal adenoma HTN", weight=60, icd_code='E26.0'),
            t('Phaeochromocytoma', 'diagnosis', 'pheochromocytoma, adrenal tumour, catecholamine excess', weight=55, icd_code='D35.0'),
            t('Acute pancreatitis', 'diagnosis', 'pancreatitis acute, pancreas inflammation, epigastric severe pain', weight=75, icd_code='K85.9'),
            t('Chronic pancreatitis', 'diagnosis', 'chronic pancreatitis, pancreatic insufficiency, pancreas damage', weight=65, icd_code='K86.1'),
            t("Crohn's disease", 'diagnosis', "Crohn's, IBD Crohn, transmural colitis, ileitis", weight=65, icd_code='K50.9'),
            t('Ulcerative colitis', 'diagnosis', 'UC, IBD ulcerative, colitis, bloody diarrhoea IBD', weight=70, icd_code='K51.9'),
            t('Coeliac disease', 'diagnosis', 'celiac disease, gluten intolerance, wheat allergy coeliac', weight=65, icd_code='K90.0'),
            t('Aortic stenosis', 'diagnosis', 'AS, aortic valve stenosis, valve stenosis aortic', weight=65, icd_code='I35.0'),
            t('Mitral stenosis', 'diagnosis', 'MS, mitral valve stenosis, rheumatic mitral', weight=65, icd_code='I05.0'),
            t('Mitral regurgitation', 'diagnosis', 'MR, mitral valve regurgitation, mitral incompetence', weight=65, icd_code='I34.0'),
            t('Dilated cardiomyopathy', 'diagnosis', 'DCM, dilated CM, dilated cardiomyopathy', weight=65, icd_code='I42.0'),
            t('Hypertrophic cardiomyopathy', 'diagnosis', 'HCM, HOCM, hypertrophic cardiomyopathy', weight=60, icd_code='I42.1'),
            t('Pulmonary arterial hypertension', 'diagnosis', 'PAH, pulmonary hypertension, high lung pressure', weight=60, icd_code='I27.0'),
            t('Cor pulmonale', 'diagnosis', 'right heart failure from lung disease, cor pulmonale', weight=60, icd_code='I27.9'),
            t('Aortic dissection', 'diagnosis', 'aortic tear, dissecting aneurysm, aortic dissection', weight=60, icd_code='I71.0'),
            t('Wilson disease', 'diagnosis', "Wilson's disease, copper metabolism disorder", weight=55, icd_code='E83.0'),
            t('Haemochromatosis', 'diagnosis', 'iron overload, hereditary haemochromatosis', weight=55, icd_code='E83.1'),
            t('Hyponatraemia', 'diagnosis', 'low sodium, serum sodium low, hyponatremia', weight=70, icd_code='E87.1'),
            t('Hypokalaemia', 'diagnosis', 'low potassium, serum potassium low, hypokalemia', weight=70, icd_code='E87.6'),
            t('Hypercalcaemia', 'diagnosis', 'high calcium, calcium excess, hypercalcemia', weight=65, icd_code='E83.5'),
            t('Diabetes insipidus', 'diagnosis', 'DI, central DI, nephrogenic DI, polydipsia polyuria', weight=60, icd_code='E23.2'),
            t('Thalassaemia trait', 'diagnosis', 'thalassaemia carrier, beta thalassaemia minor', weight=75, icd_code='D56.3'),
            t('Sickle cell trait', 'diagnosis', 'HbAS, sickle cell carrier, sickle cell anaemia', weight=70, icd_code='D57.3'),
        ]

        # ── INVESTIGATIONS (weight 60-90) ──────────────────────────────────
        items += [
            t('CBC', 'investigation', 'complete blood count, haemogram, blood test CBC, full blood count', weight=90),
            t('Haemoglobin', 'investigation', 'Hb, hemoglobin, blood count, haemoglobin level', weight=90),
            t('WBC count', 'investigation', 'white blood cell, leucocyte count, total count, TLC, WBC differential', weight=85),
            t('Platelet count', 'investigation', 'platelets, thrombocyte count, platelet level', weight=85),
            t('Peripheral blood smear', 'investigation', 'PBS, blood film, peripheral smear, malaria smear', weight=80),
            t('ESR', 'investigation', 'erythrocyte sedimentation rate, ESR test, sedimentation rate', weight=85),
            t('CRP', 'investigation', 'C-reactive protein, inflammatory marker, CRP level', weight=85),
            t('Blood culture', 'investigation', 'blood culture sensitivity, bacteraemia test, sepsis culture', weight=80),
            t('Urine routine microscopy', 'investigation', 'urine routine, urinalysis, urine RE/ME, urine test, urine examination', weight=90),
            t('Urine culture', 'investigation', 'urine C&S, urine culture sensitivity, urine bacteria', weight=85),
            t('FBS (fasting blood sugar)', 'investigation', 'fasting glucose, FBS, fasting blood sugar, sugar fasting', weight=90),
            t('PPBS (post-prandial blood sugar)', 'investigation', 'PPBS, post-prandial glucose, 2 hour sugar, post meal sugar', weight=90),
            t('RBS (random blood sugar)', 'investigation', 'random glucose, RBS, random blood sugar', weight=85),
            t('HbA1c', 'investigation', 'glycosylated haemoglobin, A1c, long term sugar, glycaemic control test', weight=90),
            t('Lipid profile', 'investigation', 'cholesterol test, lipid panel, lipids, dyslipidaemia test', weight=90),
            t('Serum creatinine', 'investigation', 'creatinine, kidney creatinine, renal creatinine', weight=90),
            t('Blood urea', 'investigation', 'urea, BUN, blood urea nitrogen, urea nitrogen', weight=85),
            t('Uric acid', 'investigation', 'serum uric acid, urate, gout test', weight=80),
            t('LFT (liver function test)', 'investigation', 'liver test, LFT, liver profile, liver function', weight=90),
            t('SGOT / AST', 'investigation', 'AST, SGOT, aspartate aminotransferase, liver enzyme', weight=85),
            t('SGPT / ALT', 'investigation', 'ALT, SGPT, alanine aminotransferase, liver enzyme', weight=85),
            t('ALP', 'investigation', 'alkaline phosphatase, ALP, bone liver enzyme', weight=80),
            t('Serum bilirubin', 'investigation', 'bilirubin, jaundice test, total direct indirect bilirubin', weight=85),
            t('Serum albumin', 'investigation', 'albumin, protein level, serum protein', weight=80),
            t('Serum electrolytes', 'investigation', 'electrolytes, sodium potassium, Na K, electrolyte panel', weight=85),
            t('Serum sodium', 'investigation', 'Na, serum sodium, sodium level', weight=85),
            t('Serum potassium', 'investigation', 'K, serum potassium, potassium level, K level', weight=85),
            t('Serum calcium', 'investigation', 'calcium, calcium level, serum calcium', weight=80),
            t('Serum magnesium', 'investigation', 'magnesium, Mg level', weight=75),
            t('Serum phosphorus', 'investigation', 'phosphorus, phosphate level, serum phosphate', weight=75),
            t('TSH', 'investigation', 'thyroid stimulating hormone, TSH level, thyroid test', weight=90),
            t('Free T3', 'investigation', 'triiodothyronine, FT3, free T3 level', weight=80),
            t('Free T4', 'investigation', 'free thyroxine, FT4, free T4 level', weight=85),
            t('Serum iron', 'investigation', 'iron level, serum iron, Fe level', weight=80),
            t('TIBC', 'investigation', 'total iron binding capacity, transferrin saturation', weight=75),
            t('Serum ferritin', 'investigation', 'ferritin, iron stores, ferritin level', weight=85),
            t('Vitamin B12', 'investigation', 'vitamin B12 level, cobalamin, B12 level', weight=85),
            t('Serum folate', 'investigation', 'folic acid level, folate, B9 level', weight=80),
            t('Vitamin D (25-OH)', 'investigation', 'vitamin D level, 25 hydroxy vitamin D, cholecalciferol level', weight=85),
            t('PT / INR', 'investigation', 'prothrombin time, INR, coagulation test, clotting time', weight=80),
            t('APTT', 'investigation', 'activated partial thromboplastin time, coagulation, clotting test', weight=75),
            t('D-dimer', 'investigation', 'D dimer, DVT test, PE test, clot marker', weight=80),
            t('Troponin I', 'investigation', 'troponin, cardiac marker, heart attack test, cardiac troponin', weight=85),
            t('Troponin T', 'investigation', 'troponin T, cardiac marker, AMI test', weight=85),
            t('CK-MB', 'investigation', 'creatine kinase MB, CK MB, cardiac enzyme', weight=80),
            t('NT-proBNP', 'investigation', 'BNP, NT-proBNP, heart failure marker, brain natriuretic peptide', weight=80),
            t('HBsAg', 'investigation', 'hepatitis B surface antigen, hepatitis B test, Hep B', weight=85),
            t('Anti-HCV', 'investigation', 'hepatitis C antibody, HCV test, Hep C test', weight=80),
            t('HIV ELISA', 'investigation', 'HIV test, AIDS test, HIV antibody, HIV ELISA', weight=80),
            t('VDRL', 'investigation', 'syphilis test, VDRL, RPR, syphilis serology', weight=75),
            t('Widal test', 'investigation', 'typhoid test, Widal, Salmonella antibody, enteric fever test', weight=85),
            t('Dengue NS1 antigen', 'investigation', 'dengue NS1, dengue antigen, dengue day 1-5 test', weight=90),
            t('Dengue IgM / IgG', 'investigation', 'dengue antibody, dengue serology, dengue late test', weight=85),
            t('Malaria RDT', 'investigation', 'malaria rapid test, malaria antigen, RDT malaria, malaria card test', weight=90),
            t('Malaria smear', 'investigation', 'malaria peripheral smear, thick thin film, malaria blood test', weight=85),
            t('COVID RT-PCR', 'investigation', 'COVID test, corona test, RTPCR, COVID RT-PCR, COVID molecular', weight=90),
            t('COVID antigen test', 'investigation', 'rapid COVID test, COVID rapid antigen, corona rapid test', weight=85),
            t('Mantoux test', 'investigation', 'tuberculin test, PPD, TB skin test, Mantoux', weight=80),
            t('Sputum AFB', 'investigation', 'sputum smear, AFB, acid fast bacilli, TB sputum test', weight=80),
            t('Sputum culture', 'investigation', 'sputum culture, respiratory culture, sputum C&S', weight=75),
            t('Chest X-ray (CXR)', 'investigation', 'CXR, chest radiograph, chest X ray, PA view, lung X ray', weight=90),
            t('ECG (12-lead)', 'investigation', 'ECG, EKG, electrocardiogram, 12 lead ECG, heart tracing', weight=90),
            t('2D Echo', 'investigation', '2D echocardiography, cardiac echo, echo, heart ultrasound', weight=85),
            t('USG abdomen', 'investigation', 'ultrasound abdomen, abdominal sonography, abdominal USG', weight=90),
            t('USG pelvis', 'investigation', 'pelvic ultrasound, USG pelvis, pelvic sonography', weight=85),
            t('USG thyroid', 'investigation', 'thyroid ultrasound, neck USG, thyroid sonography', weight=80),
            t('Mammography', 'investigation', 'mammogram, breast X-ray, breast cancer screening', weight=80),
            t('CT scan chest', 'investigation', 'CT chest, HRCT chest, lung CT, NCCT chest', weight=80),
            t('CT scan abdomen', 'investigation', 'CT abdomen, CECT abdomen, abdominal CT', weight=80),
            t('CT scan brain', 'investigation', 'brain CT, head CT, NCCT brain, cranial CT', weight=85),
            t('MRI brain', 'investigation', 'brain MRI, cranial MRI, MRI head', weight=85),
            t('MRI spine', 'investigation', 'spine MRI, spinal MRI, MRI lumbar, MRI cervical', weight=85),
            t('MRI knee', 'investigation', 'knee MRI, MRI knee joint, knee cartilage MRI', weight=80),
            t('Bone densitometry (DEXA)', 'investigation', 'DEXA scan, bone density, osteoporosis test, BMD', weight=80),
            t('Urine pregnancy test (UPT)', 'investigation', 'UPT, pregnancy test, home pregnancy test, urine pregnancy', weight=85),
            t('Beta-hCG', 'investigation', 'serum beta hCG, pregnancy quantitative, HCG level', weight=80),
            t('Pap smear', 'investigation', 'cervical smear, pap test, cervical cancer screening, Papanicolaou', weight=80),
            t('Semen analysis', 'investigation', 'sperm test, male fertility test, semen test', weight=75),
            t('Testosterone', 'investigation', 'serum testosterone, male hormone, T level', weight=75),
            t('FSH', 'investigation', 'follicle stimulating hormone, FSH level, ovarian reserve', weight=75),
            t('LH', 'investigation', 'luteinizing hormone, LH level', weight=75),
            t('Prolactin', 'investigation', 'serum prolactin, prolactin level, hyperprolactinaemia test', weight=75),
            t('DHEA-S', 'investigation', 'DHEA sulfate, adrenal androgen, DHEAS', weight=70),
            t('Cortisol (morning)', 'investigation', 'serum cortisol, morning cortisol, adrenal function', weight=70),
            t('ANA', 'investigation', 'antinuclear antibody, ANA test, autoimmune screen', weight=75),
            t('dsDNA', 'investigation', 'anti-double stranded DNA, dsDNA antibody, lupus test', weight=70),
            t('ANCA', 'investigation', 'antineutrophil cytoplasmic antibody, vasculitis test', weight=70),
            t('RF (rheumatoid factor)', 'investigation', 'rheumatoid factor, RA factor, RF test', weight=80),
            t('Anti-CCP', 'investigation', 'anti cyclic citrullinated peptide, RA antibody, CCP antibody', weight=75),
            t('HLA-B27', 'investigation', 'HLA B27, ankylosing spondylitis test, axial spondylarthropathy', weight=70),
            t('PSA (prostate specific antigen)', 'investigation', 'PSA, prostate test, prostate cancer marker', weight=80),
            t('CEA', 'investigation', 'carcinoembryonic antigen, cancer marker, colon cancer marker', weight=70),
            t('CA-125', 'investigation', 'ovarian cancer marker, CA125, ovarian marker', weight=70),
            t('CA 19-9', 'investigation', 'CA19-9, pancreatic cancer marker, biliary marker', weight=65),
            t('AFP', 'investigation', 'alpha fetoprotein, liver cancer marker, AFP level', weight=70),
            t('Serum LDH', 'investigation', 'LDH, lactate dehydrogenase, cell damage marker', weight=70),
            t('Serum amylase', 'investigation', 'amylase, pancreatitis test, pancreatic amylase', weight=75),
            t('Serum lipase', 'investigation', 'lipase, pancreatitis test, pancreatic lipase', weight=75),
            t('ABG (arterial blood gas)', 'investigation', 'arterial blood gas, ABG, acid-base status, pH pO2 pCO2', weight=75),
            t('Pulse oximetry', 'investigation', 'SpO2, oxygen saturation, pulse ox, fingertip oximeter', weight=85),
            t('Spirometry', 'investigation', 'lung function test, FEV1, FVC, spirometry test, PFT', weight=80),
            t('Peak flow meter', 'investigation', 'PEFR, peak expiratory flow, peak flow, asthma monitoring', weight=80),
            t('Holter monitoring', 'investigation', 'Holter, 24-hour ECG, ambulatory ECG, arrhythmia monitoring', weight=75),
            t('TMT (treadmill test)', 'investigation', 'treadmill test, stress test, exercise ECG, TMT', weight=80),
            t('Stress echocardiography', 'investigation', 'stress echo, dobutamine stress echo, exercise echo', weight=70),
            t('Upper GI endoscopy', 'investigation', 'gastroscopy, OGD scope, upper endoscopy, EGD', weight=80),
            t('Colonoscopy', 'investigation', 'colon scope, large intestine endoscopy, lower GI scope', weight=75),
            t('ERCP', 'investigation', 'bile duct scope, ERCP, endoscopic cholangiopancreatography', weight=65),
            t('Liver biopsy', 'investigation', 'hepatic biopsy, liver histology, liver biopsy', weight=65),
            t('Kidney biopsy', 'investigation', 'renal biopsy, renal histology, kidney biopsy', weight=65),
            t('Bone marrow biopsy', 'investigation', 'bone marrow, trephine biopsy, haematology biopsy', weight=65),
            t('FNAC', 'investigation', 'fine needle aspiration, FNAC, needle biopsy, cytology', weight=75),
            t('Skin biopsy', 'investigation', 'skin histology, dermal biopsy, punch biopsy', weight=70),
            t('NCS (nerve conduction study)', 'investigation', 'nerve test, NCS, nerve conduction velocity, NCS EMG', weight=75),
            t('EMG', 'investigation', 'electromyography, muscle nerve test, EMG NCS', weight=70),
            t('EEG', 'investigation', 'electroencephalogram, brain wave test, seizure EEG', weight=75),
            t('Lumbar puncture (CSF analysis)', 'investigation', 'LP, spinal tap, CSF, lumbar puncture, cerebrospinal fluid', weight=75),
            t('Ophthalmology referral', 'investigation', 'eye specialist, retina check, ophthalmology, eye examination referral', weight=75),
            t('Fundus examination', 'investigation', 'fundoscopy, retinal exam, fundus exam, direct ophthalmoscopy', weight=75),
            t('Audiometry', 'investigation', 'hearing test, audiogram, pure tone audiometry', weight=70),
            t('Tympanometry', 'investigation', 'tympanogram, middle ear test, eardrum mobility', weight=65),
            t('Skin prick test', 'investigation', 'allergy test, prick test, allergen test, skin allergy test', weight=70),
            t('Serum IgE', 'investigation', 'total IgE, allergy IgE, atopy test, immunoglobulin E', weight=70),
            t('Stool occult blood', 'investigation', 'FOB, fecal occult blood, occult blood stool, hidden blood stool', weight=75),
            t('H. pylori antigen (stool)', 'investigation', 'H pylori stool antigen, Helicobacter pylori test', weight=80),
            t('H. pylori breath test', 'investigation', 'urea breath test, H pylori breath, UBT', weight=75),
            t('eGFR', 'investigation', 'estimated GFR, kidney filtration rate, glomerular filtration', weight=85),
            t('Urine protein creatinine ratio', 'investigation', 'uPCR, protein creatinine ratio, spot urine protein', weight=75),
            t('24-hour urine protein', 'investigation', '24 hour urine, proteinuria quantification, protein 24h', weight=75),
            t('Carotid Doppler', 'investigation', 'carotid ultrasound, Doppler carotid, carotid stenosis test', weight=70),
            t('Peripheral Doppler', 'investigation', 'peripheral vascular Doppler, limb Doppler, PVD test', weight=70),
            t('Bone scan', 'investigation', 'nuclear bone scan, bone scintigraphy, bone metastasis scan', weight=65),
            t('PET scan', 'investigation', 'PET CT, positron emission tomography, cancer staging scan', weight=65),
            t('Thyroid antibodies', 'investigation', 'TPO antibody, thyroglobulin antibody, anti-TPO, thyroid autoantibodies', weight=75),
        ]

        # ── ADVICE (weight 70-85) ──────────────────────────────────────────
        items += [
            t('Plenty of oral fluids', 'advice', 'paani piyo, hydration, pani pina, fluids plenty', weight=85),
            t('Drink at least 3 litres of water daily', 'advice', 'paani 3 litre, zyada paani piyo, hydration 3L', weight=85),
            t('Warm salt water gargling', 'advice', 'garara karo, namak pani gargle, salt water gargle, gale ke liye gargle', weight=85),
            t('Steam inhalation twice daily', 'advice', 'bhap lo, steam inhalation, steam twice, inhale steam', weight=85),
            t('Complete bed rest for 2-3 days', 'advice', 'araam karo, bed rest, complete rest 3 din', weight=85),
            t('Light diet — khichdi / rice and dal', 'advice', 'halka khaana, khichdi, dahi chawal, light food, soft diet', weight=85),
            t('Avoid oily and spicy food', 'advice', 'tel masala mat khao, greasy food band, spicy food avoid, oily food nahi', weight=85),
            t('Avoid outside food', 'advice', 'bahar ka khaana band, restaurant food avoid, outside food nahi', weight=80),
            t('Avoid cold drinks and ice cream', 'advice', 'thanda mat piyo, cold drinks band, ice cream avoid', weight=80),
            t('Low salt diet (< 2g sodium/day)', 'advice', 'namak kam khao, low salt diet, sodium restrict, salt free', weight=85),
            t('Low fat diet', 'advice', 'fat kam khao, less oil, low fat food', weight=80),
            t('High fibre diet', 'advice', 'fiber diet, vegetables fruits diet, high fibre, sabzi khao', weight=80),
            t('Avoid alcohol completely', 'advice', 'sharaab band, alcohol avoid completely, no alcohol', weight=85),
            t('Avoid smoking', 'advice', 'beedi sigaret band, smoking band, cigarette avoid, tobacco avoid', weight=85),
            t('Avoid alcohol and smoking', 'advice', 'sharaab aur sigaret dono band, alcohol smoking avoid', weight=85),
            t('Regular exercise 30 minutes daily', 'advice', 'exercise karo, roz exercise, 30 min exercise daily', weight=85),
            t('Brisk walking 30-45 minutes daily', 'advice', 'walk karo, morning walk, brisk walk 30 min, tez chalna', weight=85),
            t('Weight reduction advised', 'advice', 'wajan kam karo, weight loss, motapa kam karo, BMI reduce', weight=85),
            t('Maintain ideal body weight', 'advice', 'ideal weight maintain, BMI normal, healthy weight', weight=80),
            t('Monitor blood pressure at home', 'advice', 'BP ghar par napo, BP monitor karo, home BP check', weight=85),
            t('Blood sugar monitoring at home', 'advice', 'sugar ghar par napo, glucose check karo, home sugar test', weight=85),
            t('Keep wound clean and dry', 'advice', 'zakhm saaf rakhna, wound clean, dressing clean', weight=80),
            t('Dressing to be changed daily', 'advice', 'patti roz badlo, daily dressing change, bandage change', weight=80),
            t('Avoid sun exposure', 'advice', 'dhoop se bachao, sun avoid, UV protection, sun exposure avoid', weight=75),
            t('Use sunscreen SPF 30+', 'advice', 'sunscreen lagao, SPF 30 sunscreen, sun protection cream', weight=75),
            t('Wear loose cotton clothing', 'advice', 'dhila kapda pahno, cotton kapda, loose clothes, comfortable wear', weight=75),
            t('Avoid scratching the affected area', 'advice', 'khujlaio mat, mat kharochna, do not scratch, rash mat khujao', weight=80),
            t('Elevate affected limb', 'advice', 'pair upar rakhna, limb elevate, limb raise, leg elevation', weight=80),
            t('Warm compresses to affected area', 'advice', 'garma patti, hot compress, senkna, warm fomentation', weight=75),
            t('Cold compresses to affected area', 'advice', 'ice lagao, cold compress, ice pack', weight=75),
            t('Regular meals — do not skip meals', 'advice', 'khaana niyamit khao, meal skip mat karo, regular eating, khana mat bhulo', weight=80),
            t('Small frequent meals', 'advice', 'chhoti chhoti meal lo, frequent small meals, 5-6 small meals', weight=80),
            t('Avoid lying down immediately after meals', 'advice', 'khane ke baad mat leto, stay upright after eating, acid reflux advice', weight=80),
            t('Head elevation during sleep', 'advice', 'sir utha ke so, elevated pillow, head raised sleeping, GERD sleep advice', weight=75),
            t('Continue medicines as prescribed', 'advice', 'dawai poori lo, medicine regularly lo, dawai band mat karo', weight=85),
            t('Do not stop medicines without doctor advice', 'advice', 'dawai khud band mat karo, doctor se poocho before stopping, medicine compliance', weight=85),
            t('Medicine compliance is very important', 'advice', 'dawai lena zaroori hai, compliance important, medicines properly', weight=85),
            t('Report immediately if fever > 102°F', 'advice', 'zyada bukhar hone par milna, 104 bukhar alert, fever worsening advice', weight=85),
            t('Report if breathing difficulty develops', 'advice', 'sans ki takleef hone par aao, SOB alert, breathlessness warning', weight=85),
            t('Report if chest pain worsens', 'advice', 'seene mein dard badhne par milna, chest pain alert, cardiac alert', weight=85),
            t('Return if symptoms do not improve in 3 days', 'advice', '3 din mein theek nahi to aao, no improvement return, review SOS', weight=85),
            t('Follow up after 1 week', 'advice', '1 hafte mein milna, 1 week review, follow up after week', weight=85),
            t('Follow up after 2 weeks', 'advice', '2 hafte mein milna, 2 weeks review, fortnight follow up', weight=85),
            t('Follow up after 1 month', 'advice', '1 mahine mein milna, monthly follow up, 4 weeks review', weight=85),
            t('Bring all reports on next visit', 'advice', 'reports laana, test results laana, previous reports laao', weight=80),
            t('Dental hygiene — brush twice daily', 'advice', 'daant saaf karo, brush do baar, dental care, oral hygiene', weight=75),
            t('Regular antenatal checkup', 'advice', 'ANC checkup regular, pregnancy checkup niyamit, antenatal visit', weight=85),
            t('Avoid heavy lifting', 'advice', 'bhari cheez mat uthao, heavy lifting avoid, strain avoid', weight=80),
            t('Pelvic floor exercises (Kegel exercises)', 'advice', 'kegel exercise, pelvic floor, urinary control exercise', weight=75),
            t('Low purine diet (avoid red meat / organ meat / seafood)', 'advice', 'purine kam khao, gout diet, red meat avoid, organ meat avoid, seafood limit', weight=75),
            t('Drink 2-3 litres water daily (for renal stones)', 'advice', 'kidney stone paani, stone ke liye paani zyada, stone prevent hydration', weight=80),
            t('Adequate calcium and vitamin D intake', 'advice', 'calcium khao, vitamin D lo, bone health diet, calcium vitamin D', weight=75),
            t('Weight-bearing exercise for bone health', 'advice', 'bone ke liye exercise, weight bearing walk, osteoporosis exercise', weight=70),
            t('Eye protection — use UV-protective glasses', 'advice', 'aankhon ke liye sunglasses, UV protection eyes, eye care glasses', weight=70),
            t('Diabetic foot care — inspect feet daily', 'advice', 'diabetic paon ki dekh rekh, foot inspection daily, DM foot care', weight=80),
            t('Wear well-fitting footwear', 'advice', 'achha joota pahno, proper footwear, fitting shoes diabetic', weight=75),
            t('Perineal hygiene', 'advice', 'private parts saaf rakhna, perineal hygiene, genital hygiene', weight=75),
            t('Use cotton innerwear', 'advice', 'suti kapde pahno, cotton underwear, cotton inner garments', weight=70),
            t('Condom use advised', 'advice', 'condom use, barrier contraception, safe sex contraception', weight=75),
            t('Safe sex practices', 'advice', 'safe sex, STI prevention, condom barrier method, safe intercourse', weight=75),
            t('Isolation for 5 days (COVID)', 'advice', 'COVID isolation, home isolation 5 days, quarantine COVID', weight=80),
            t('Mask use in public', 'advice', 'mask pehno, face mask, public masking, respiratory precautions', weight=80),
            t('Hand hygiene — wash hands frequently', 'advice', 'haath dhona, hand washing, hygiene hands, sanitize hands', weight=80),
            t('Mosquito protection — use repellent / net', 'advice', 'machchar se bachao, mosquito repellent, mosquito net, bed net', weight=80),
            t('Boil drinking water', 'advice', 'paani ubaal ke piyo, boil water, safe water, drinking water safe', weight=80),
            t('Use ORS for fluid replacement', 'advice', 'ORS piyo, electral, ORS for diarrhoea, nimbu namak pani, oral rehydration', weight=85),
            t('Oral rehydration solution (ORS) preparation', 'advice', 'ORS banane ka tarika, ORS instructions, home ORS recipe', weight=80),
            t('Avoid driving / operating machinery (sedating medication)', 'advice', 'gaadi mat chalao, heavy machinery avoid, driving restriction medicines', weight=80),
            t('Do not operate heavy machinery on these medicines', 'advice', 'machine mat chalao, sedating drug caution, drowsy medicine', weight=75),
            t('Nasal saline drops as needed', 'advice', 'naak mein drops, saline nasal, nasal rinse, naak saaf karo', weight=75),
        ]

        # ── PROCEDURES (weight 60-75) ─────────────────────────────────────
        items += [
            t('Nebulisation', 'procedure', 'nebulizer, bronchodilator nebulisation, salbutamol nebulisation', weight=75),
            t('IV access', 'procedure', 'IV line, intravenous access, cannula, IV cannulation', weight=75),
            t('IV fluids', 'procedure', 'intravenous fluids, IV drip, NS drip, RL drip, fluid administration', weight=75),
            t('Blood transfusion', 'procedure', 'blood transfuse, packed cell transfusion, PRBC', weight=70),
            t('Platelet transfusion', 'procedure', 'platelet give, platelet transfuse, thrombocyte transfusion', weight=70),
            t('Fresh frozen plasma', 'procedure', 'FFP transfusion, plasma transfusion, FFP', weight=65),
            t('IM injection', 'procedure', 'intramuscular injection, IM shot, IM route', weight=75),
            t('SC injection', 'procedure', 'subcutaneous injection, SC route, under skin injection', weight=70),
            t('Wound suturing', 'procedure', 'suture wound, stitch wound, suturing, laceration repair', weight=70),
            t('Wound debridement', 'procedure', 'clean wound, debride, wound cleaning, necrotic tissue removal', weight=65),
            t('Abscess I&D', 'procedure', 'incision and drainage, I&D, abscess drain, pus drain', weight=70),
            t('Burn dressing', 'procedure', 'burn wound dressing, burns management, burn care', weight=65),
            t('Ear syringing', 'procedure', 'ear wax remove, ear syringe, cerumen removal', weight=65),
            t('Ear wicking', 'procedure', 'ear wick, otitis externa wick, ear canal wick', weight=60),
            t('Nasal packing', 'procedure', 'epistaxis packing, nasal pack, nose bleed pack', weight=65),
            t('Foreign body removal', 'procedure', 'FB removal, remove foreign body, foreign object remove', weight=65),
            t('Urinary catheterisation', 'procedure', 'catheter, Foley catheter, urinary catheter, bladder drain', weight=70),
            t('Nasogastric tube insertion', 'procedure', 'NGT, nasogastric tube, NG tube insertion, Ryles tube', weight=65),
            t('Chest tube insertion', 'procedure', 'ICD, intercostal drain, chest drain, thoracic drain', weight=65),
            t('Intercostal drainage', 'procedure', 'ICD, chest drain, pleural drain, intercostal tube drain', weight=65),
            t('Paracentesis', 'procedure', 'ascites tap, abdominal paracentesis, ascitic tap', weight=65),
            t('Thoracocentesis', 'procedure', 'pleural tap, pleurocentesis, thoracentesis, chest tap', weight=65),
            t('Lumbar puncture', 'procedure', 'LP, spinal tap, CSF tap, lumbar puncture procedure', weight=65),
            t('Intra-articular injection', 'procedure', 'joint injection, intra-articular steroid, joint steroid', weight=65),
            t('Corticosteroid injection', 'procedure', 'steroid shot, cortisone injection, depo medrol injection', weight=65),
            t('POP cast', 'procedure', 'plaster cast, POP, fracture cast, below knee cast', weight=65),
            t('Splinting', 'procedure', 'splint, back slab, fracture splint, POP slab', weight=65),
            t('Appendectomy', 'procedure', 'appendix operation, appendix remove, laparoscopic appendectomy', weight=65),
            t('Cholecystectomy', 'procedure', 'gallbladder remove, laparoscopic cholecystectomy, gallstone operation', weight=65),
            t('Hernia repair', 'procedure', 'hernioplasty, hernia surgery, hernia operation', weight=65),
            t('D&C', 'procedure', 'dilation curettage, D&C procedure, uterine curettage', weight=65),
            t('Hysterectomy', 'procedure', 'uterus remove, hysterectomy operation, womb removal', weight=65),
            t('LSCS', 'procedure', 'C-section, caesarean, lower segment caesarean section, LSCS procedure', weight=65),
            t('Normal vaginal delivery', 'procedure', 'NVD, normal delivery, vaginal birth', weight=65),
            t('Episiotomy', 'procedure', 'perineal cut, episiotomy procedure', weight=60),
            t('IUD insertion', 'procedure', 'copper T insertion, IUCD, intrauterine device, copper T', weight=65),
            t('Colposcopy', 'procedure', 'cervical colposcopy, colposcopy procedure, cervical examination', weight=65),
            t('LEEP', 'procedure', 'loop electrosurgical excision, LEEP procedure, CIN treatment', weight=60),
            t('Endoscopy', 'procedure', 'upper GI endoscopy, gastroscopy procedure, OGD scope', weight=70),
            t('Bronchoscopy', 'procedure', 'lung scope, bronchoscopy procedure, airway scope', weight=60),
            t('Cystoscopy', 'procedure', 'bladder scope, cystoscopy procedure, urethral scope', weight=60),
            t('PCNL', 'procedure', 'kidney stone removal surgery, percutaneous nephrolithotomy', weight=60),
            t('TURP', 'procedure', 'prostate surgery, TURP procedure, transurethral resection prostate', weight=60),
            t('Trigger point injection', 'procedure', 'muscle injection, trigger point, myofascial injection', weight=60),
            t('ORIF', 'procedure', 'open reduction internal fixation, fracture surgery, bone surgery ORIF', weight=60),
            t('Circumcision', 'procedure', 'male circumcision, khitan, sunat, foreskin removal', weight=60),
            t('Vasectomy', 'procedure', 'male sterilisation, vasectomy, male family planning', weight=60),
            t('Tubal ligation', 'procedure', 'female sterilisation, tubectomy, tubal ligation, band aid', weight=60),
        ]

        total = len(items)
        MedicalTerm.objects.bulk_create(items, ignore_conflicts=True)

        from django.db.models import Count
        counts = MedicalTerm.objects.values('category').annotate(n=Count('id'))
        self.stdout.write('Terms by category:')
        for c in sorted(counts, key=lambda x: x['category']):
            self.stdout.write(f"  {c['category']}: {c['n']}")
        self.stdout.write(self.style.SUCCESS(f'Seeded {total} medical terms successfully.'))
